import fs from "node:fs";
import path from "node:path";
import {
  expect,
  type Page,
  type Locator,
  errors as playwrightErrors,
} from "@playwright/test";
import { chatModels, type ChatModel } from "@/lib/ai/models";

/**
 * Validate that the current page URL ends with a chat identifier without
 * coupling the assertion to a specific host or port. Playwright drives the app
 * on a dynamic base URL (port 3000 locally, 3100 during hermetic runs), so we
 * only assert on the `/chat/:id` suffix. The UUID shape mirrors the database
 * identifiers generated by Drizzle.
 */
const CHAT_ID_REGEX = /\/chat\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

/**
 * Streaming requests reuse the chat API namespace but append the chat
 * identifier before `/stream`. We match both the base route and streaming
 * suffix so the helper recognises edits and retries as well as brand new
 * chats, regardless of the query string Playwright attaches when retrying.
 */
const CHAT_STREAM_PATH_REGEX = /^\/api\/chat\/[\w-]+\/stream$/;

/**
 * Some Playwright runs rely on the automation toast bridge when the Sonner
 * portal hydrates slowly. Target both the native toast and the bridge element
 * so locator queries remain stable even when the fallback is active.
 */
const TOAST_LOCATOR = '[data-testid="toast"], #automation-toast-bridge';

/**
 * Snapshot of the assistant timeline captured right before triggering a new
 * generation. Defining the shape up front allows helper methods to reference
 * the type without relying on the `this` context — a pattern that keeps the
 * file compliant with `noImplicitThis` during the Next.js type-checking phase.
 */
type AssistantSnapshot = {
  count: number;
  latestMessageId: string | null;
  latestMessageText: string;
  latestArtifactCount: number;
};

export class ChatPage {
  /**
   * Surface the Playwright assertion helper so unit tests can substitute a
   * lightweight spy without mutating the imported module namespace.
   */
  static expect = expect;

  private readonly page: Page;

  /**
   * Snapshot of the assistant timeline captured right before triggering a new
   * generation. We compare the stored baseline with the live DOM while polling
   * so the helper recognises both brand-new bubbles and updates to the latest
   * message content or attached artefacts.
   */
  private pendingAssistantSnapshot: AssistantSnapshot | null = null;

  /**
   * Track the most recent vote request so the helper can await the matching
   * `/api/vote` response and avoid relying solely on transient UI signals.
   */
  private pendingVoteRequest: Promise<void> | null = null;

  /**
   * Record how many user messages were present before dispatching the current
   * action. Suggested quick actions append the bubble immediately while the UI
   * may still be hydrating its streaming indicators. Falling back to this
   * counter lets the polling guard unblock as soon as the DOM reflects the
   * optimistic user echo, even if the stop button or spinner never toggles.
   */
  private pendingUserMessageCount = 0;

  /**
   * Record whether the stop button was visible when the next generation cycle
   * started so polling can differentiate between the residual cooldown from the
   * previous run and a fresh streaming toggle.
   */
  private pendingStopButtonWasVisible = false;

  /**
   * Record the send button visibility before dispatching a message so the UI
   * polling fallback can recognise when the stop control takes over, even if
   * the spinner fails to render during fast hermetic runs.
   */
  private pendingSendButtonWasVisible = false;

  /**
   * Preserve the send button enabled state before dispatching a prompt. Certain
   * automation flows (for example suggested quick actions) keep the control
   * visible yet disable it instead of swapping in the stop button. Capturing the
   * baseline enabled flag allows the polling fallback to treat that transition
   * as proof that streaming started even when visibility stays unchanged.
   */
  private pendingSendButtonWasEnabled = false;

  constructor(page: Page) {
    this.page = page;
  }

  get sendButton() {
    return this.page.getByTestId("send-button");
  }

  get stopButton() {
    return this.page.getByTestId("stop-button");
  }

  get multimodalInput() {
    return this.page.getByTestId("multimodal-input");
  }

  get scrollContainer() {
    return this.page.locator(".overflow-y-scroll");
  }

  get scrollToBottomButton() {
    return this.page.getByTestId("scroll-to-bottom-button");
  }

  async createNewChat() {
    await this.page.goto("/chat", {
      /**
       * Next.js app router streams the shell before every asset finishes
       * loading, which occasionally blocks the `load` event during cold Turbopack
       * starts. Waiting for `domcontentloaded` keeps the navigation resilient in
       * hermetic Playwright runs without masking legitimate network hangs.
       */
      waitUntil: "domcontentloaded",
    });

    await this.ensureChatSurfaceReady();
  }

  /**
   * Confirm that the chat surface rendered after navigation. The helper guards
   * against authentication regressions (a redirect to `/login`) and ensures the
   * input controls are visible before callers attempt to interact with them.
   */
  private async ensureChatSurfaceReady() {
    const currentUrl = new URL(this.page.url());

    if (currentUrl.pathname.startsWith("/login")) {
      throw new Error(
        "Expected an authenticated session before visiting /chat, but the app redirected to /login. " +
          "Ensure tests/setup/auth.setup.ts provisioned credentials via the regular sign-in flow."
      );
    }

    await this.page.waitForSelector('[data-testid="multimodal-input"]', {
      /**
       * Chat renders a sizeable component tree. Waiting for the primary input
       * avoids racing against hydration when Playwright runs in parallel.
       */
      state: "visible",
      timeout: 15_000,
    });

    await this.page.waitForSelector('[data-testid="send-button"]', {
      state: "visible",
      timeout: 15_000,
    });
  }

  getCurrentURL(): string {
    return this.page.url();
  }

  async sendUserMessage(message: string) {
    await this.waitForComposerReady(message);

    await this.prepareForGeneration();

    /**
     * Trigger the send action and the API wait concurrently so we capture the
     * network response associated with this submission. Surfacing transport
     * failures immediately makes the suite easier to debug than waiting for the
     * streaming assertions to eventually time out.
     */
    await Promise.all([
      this.waitForChatApiResponse(),
      this.sendButton.click(),
    ]);
  }

  async isGenerationComplete() {
    const assistantMessages = this.page.getByTestId("message-assistant");
    const {
      count: initialAssistantCount,
      latestMessageId: initialLatestMessageId,
      latestMessageText: initialLatestMessage,
      latestArtifactCount: initialArtifactCount,
    } =
      this.pendingAssistantSnapshot ??
      (await this.captureAssistantSnapshot());

    this.pendingAssistantSnapshot = null;
    /**
     * Finance journeys often render artefacts (chart, backtest, news) without
     * adding textual content to the assistant bubble. Tracking the initial
     * artefact footprint lets us confirm the UI updated even when the message
     * copy stays empty – a scenario that previously caused the polling loop to
     * spin forever and eventually time out the Playwright run.
     */

    /**
     * Some chat journeys (notably the finance accessibility sweep) reuse the
     * same assistant bubble when multiple prompts run back to back. The DOM
     * still streams fresh content, but the overall assistant count remains
     * stable. Poll both the count and the text payload so we unblock as soon as
     * either a new bubble appears or the latest response finishes streaming.
     */
    await this.page.waitForFunction(
      (args: {
        initialAssistantCount: number;
        initialLatestMessageId: string | null;
        initialLatestMessage: string;
        initialArtifactCount: number;
      }) => {
        const {
          initialAssistantCount,
          initialLatestMessageId,
          initialLatestMessage,
          initialArtifactCount,
        } = args;

        const toast = document.querySelector<HTMLElement>('[data-testid="toast"]');
        const toastText = toast?.textContent?.trim() ?? '';
        if (toastText.length > 0) {
          throw new Error(
            `Chat surfaced an error toast while waiting for the assistant response: ${toastText}`
          );
        }

        const assistantNodes = Array.from(
          document.querySelectorAll<HTMLElement>('[data-testid="message-assistant"]')
        );
        const currentCount = assistantNodes.length;

        if (currentCount > initialAssistantCount) {
          return true;
        }

        if (currentCount === initialAssistantCount && currentCount > 0) {
          const latestAssistant = assistantNodes[currentCount - 1];
          const latestMessageId = latestAssistant.getAttribute('data-message-id');

          if (latestMessageId && latestMessageId !== initialLatestMessageId) {
            return true;
          }

          const latestContent =
            latestAssistant
              .querySelector<HTMLElement>('[data-testid="message-content"]')
              ?.innerText.trim() ?? '';

          if (latestContent.length > 0 && latestContent !== initialLatestMessage) {
            return true;
          }

          const latestArtifactCount = latestAssistant.querySelectorAll('[data-testid$="-artifact"]').length;

          if (latestArtifactCount > initialArtifactCount) {
            return true;
          }

          const loadingCount = document.querySelectorAll('[data-testid="message-assistant-loading"]').length;
          const stopButton = document.querySelector<HTMLElement>('[data-testid="stop-button"]');
          const stopVisible =
            !!stopButton &&
            stopButton.offsetParent !== null &&
            window.getComputedStyle(stopButton).visibility !== 'hidden';

          if (stopVisible) {
            /**
             * Inline edit submissions reuse the global composer state. When the
             * stop button is visible we know the chat helpers started
             * streaming, so the fallback can return immediately without
             * waiting for additional DOM signals.
             */
            return true;
          }

          if (loadingCount === 0 && !stopVisible) {
            return true;
          }
        }

        return false;
      },
      {
        initialAssistantCount,
        initialLatestMessageId,
        initialLatestMessage,
        initialArtifactCount,
      },
      { timeout: 60_000 }
    );

    /**
     * The assistant stream reuses the same container while piping tool results
     * into the UI. By the time we reach this section the guard above has either
     * observed a brand-new bubble or detected fresh content within the latest
     * one, so selecting `count() - 1` safely targets the resolved response even
     * when earlier interactions left history entries in the DOM.
     */

    const latestAssistantMessage = assistantMessages.nth(
      (await assistantMessages.count()) - 1
    );
    await latestAssistantMessage.waitFor({ state: "attached" });

    await expect(this.page.getByTestId("message-assistant-loading")).toHaveCount(0);
    await expect(this.page.getByTestId("stop-button")).toHaveCount(0);

    const sendButton = this.sendButton;
    await expect(sendButton).toBeVisible();

    const latestMessageContent = latestAssistantMessage.getByTestId(
      "message-content"
    );

    let previousText = "";
    let stableIterations = 0;

    for (let attempt = 0; attempt < 50; attempt++) {
      const currentText = (await latestMessageContent.innerText()).trim();

      if (currentText && currentText === previousText) {
        stableIterations += 1;
        if (stableIterations >= 2) {
          break;
        }
      } else {
        stableIterations = 0;
        previousText = currentText;
      }

      await this.page.waitForTimeout(200);
    }

    const [finalText, finalArtifactCount] = await Promise.all([
      latestMessageContent.innerText().then((value) => value.trim()),
      latestAssistantMessage
        .locator('[data-testid$="-artifact"]')
        .count()
        .catch(() => 0),
    ]);

    /**
     * Artefact-only responses intentionally leave the chat bubble empty while
     * rendering dedicated finance components. Accept either textual deltas or
     * newly attached artefacts so both interaction styles satisfy the
     * completion contract.
     */
    expect(finalText.length > 0 || finalArtifactCount > 0).toBe(true);
  }

  async isVoteComplete(direction: "up" | "down" = "up") {
    /**
     * Voting triggers a toast notification via `toast.promise`. Waiting on the
     * visual feedback keeps the helper independent from the underlying fetch
     * request so the e2e suite remains hermetic and does not rely on network
     * responses resolving.
     */
    const voteButton = this.page.getByTestId(
      direction === "up" ? "message-upvote" : "message-downvote"
    );

    const toast = this.page.locator(TOAST_LOCATOR).first();
    const successCopy =
      direction === "up" ? "Upvoted Response!" : "Downvoted Response!";

    /**
     * Sonner silently drops toast updates when another notification is already
     * visible. Rather than timing out the suite when the success toast never
     * renders, attempt to observe it with a short grace period and fall back to
     * the button state if the toast is skipped.
     */
    const toastAppeared = await toast
      .waitFor({ state: "visible", timeout: 2_000 })
      .then(() => true)
      .catch(() => false);

    if (toastAppeared) {
      await ChatPage.expect(toast).toContainText(successCopy);
    }

    if (this.pendingVoteRequest) {
      try {
        await this.pendingVoteRequest;
      } finally {
        this.pendingVoteRequest = null;
      }
    }

    /**
     * SWR mutates the cached vote state in the background. Give the UI a few
     * moments to reflect the disabled state locally before falling back to the
     * optimistic network confirmation above.
     */
    const disableDeadline = Date.now() + 10_000;
    while (Date.now() < disableDeadline) {
      if (await voteButton.isDisabled()) {
        return;
      }

      await this.page.waitForTimeout(200);
    }
  }

  async hasChatIdInUrl() {
    await expect(this.page).toHaveURL(CHAT_ID_REGEX);
  }

  async sendUserMessageFromSuggestion() {
    /**
     * Target the deterministic suggestion test identifier so the helper keeps
     * working even when the rendered label changes (for example due to
     * different font fallbacks in offline Playwright runs).
     */
    const suggestion = this.page.getByTestId("suggested-action-0");
    await ChatPage.expect(suggestion).toBeVisible({ timeout: 15_000 });

    const userMessages = this.page.getByTestId("message-user");
    const initialUserCount = await userMessages.count();

    await this.prepareForGeneration();

    await Promise.all([
      this.waitForChatApiResponse(),
      suggestion.click(),
    ]);

    try {
      await ChatPage.expect(userMessages).toHaveCount(initialUserCount + 1, {
        timeout: 5_000,
      });
    } catch (error) {
      const composerValue = await this.multimodalInput
        .inputValue()
        .catch(() => "");
      const diagnostic =
        composerValue.trim().length > 0
          ? ` Composer retained value: "${composerValue}".`
          : " Composer remained empty.";

      throw new Error(
        "Timed out waiting for the suggested action to append a user message." +
          diagnostic,
        error instanceof Error ? { cause: error } : undefined
      );
    }
  }

  async isElementVisible(elementId: string) {
    await expect(this.page.getByTestId(elementId)).toBeVisible();
  }

  async isElementNotVisible(elementId: string) {
    await expect(this.page.getByTestId(elementId)).not.toBeVisible();
  }

  async addImageAttachment() {
    const attachmentsButton = this.page.getByTestId("attachments-button");

    /**
     * Reasoning models disable file uploads in the composer. When the current
     * chat session uses that model, temporarily switch back to the default
     * conversational model so the attachment preview renders just like it does
     * in production. This mirrors the behaviour a user would follow manually
     * and keeps the Playwright journey deterministic.
     */
    if (await attachmentsButton.isDisabled()) {
      const fallbackModel =
        chatModels.find((model) => model.id === "chat-model") ?? chatModels[0];

      if (!fallbackModel) {
        throw new Error("Unable to determine the default chat model");
      }

      await this.chooseModelFromSelector(fallbackModel.id);
      await expect(attachmentsButton).toBeEnabled();
    }

    this.page.on("filechooser", async (fileChooser) => {
      const filePath = path.join(
        process.cwd(),
        "public",
        "images",
        "mouth of the seine, monet.jpg"
      );
      const imageBuffer = fs.readFileSync(filePath);

      await fileChooser.setFiles({
        name: "mouth of the seine, monet.jpg",
        mimeType: "image/jpeg",
        buffer: imageBuffer,
      });
    });

    await attachmentsButton.click();
  }

  async getSelectedModel() {
    const modelId = await this.page.getByTestId("model-selector").innerText();
    return modelId;
  }

  async chooseModelFromSelector(chatModelId: string) {
    const chatModel = chatModels.find(
      (currentChatModel) => currentChatModel.id === chatModelId
    );

    if (!chatModel) {
      throw new Error(`Model with id ${chatModelId} not found`);
    }

    const selectorTrigger = this.page.getByTestId("model-selector");

    // Wait for the selector trigger to hydrate before attempting to interact.
    await expect(selectorTrigger).toBeVisible({ timeout: 60_000 });
    await expect(selectorTrigger).toBeEnabled();

    await selectorTrigger.click();

    const selectorItem = await this.resolveModelSelectorItem({
      chatModel,
      timeoutMs: 60_000,
    });

    await expect(selectorItem).toBeVisible({ timeout: 60_000 });
    await selectorItem.click();

    expect(await this.getSelectedModel()).toBe(chatModel.name);
  }

  async getSelectedVisibility() {
    const visibilityId = await this.page
      .getByTestId("visibility-selector")
      .innerText();
    return visibilityId;
  }

  async chooseVisibilityFromSelector(chatVisibility: "public" | "private") {
    await this.page.getByTestId("visibility-selector").click();
    await this.page
      .getByTestId(`visibility-selector-item-${chatVisibility}`)
      .click();
    expect(await this.getSelectedVisibility()).toBe(chatVisibility);
  }

  async getRecentAssistantMessage() {
    const messageElements = await this.page
      .getByTestId("message-assistant")
      .all();
    const lastMessageElement = messageElements.at(-1);

    if (!lastMessageElement) {
      throw new Error("No assistant message found");
    }

    const content = await lastMessageElement
      .getByTestId("message-content")
      .innerText()
      .then((value) => value?.trim() ?? "")
      .catch(() => "");

    const reasoningContainer = lastMessageElement.getByTestId(
      "message-reasoning"
    );
    const reasoningTrigger = lastMessageElement.getByTestId(
      "message-reasoning-trigger"
    );
    const reasoningContent = lastMessageElement.getByTestId(
      "message-reasoning-content"
    );

    const reasoningText = await reasoningContent
      .waitFor({ state: "attached", timeout: 5_000 })
      .then(async () => {
        const isVisible = await reasoningContent
          .isVisible()
          .catch(() => false);

        if (!isVisible) {
          // Auto-close animations hide the reasoning snippet almost
          // immediately after streaming finishes. Re-open the accordion so we
          // can capture the full explanation before returning it to callers.
          await reasoningTrigger.click();
          await reasoningContent.waitFor({ state: "visible", timeout: 5_000 });
        }

        return reasoningContent
          .innerText()
          .then((value) => value?.trim() ?? "")
          .catch(() => null);
      })
      .catch(() => null);

    const self = this;

    return {
      element: lastMessageElement,
      content,
      reasoning: reasoningText,
      reasoningElement: reasoningContainer,
      async toggleReasoningVisibility() {
        const currentState = await reasoningContent
          .getAttribute("data-state")
          .catch(() => null);

        await reasoningTrigger.click();

        // Defensive guard: if the attribute is missing we bail out rather
        // than waiting forever on an assertion that would never settle.
        if (!currentState) {
          return;
        }

        const nextState = currentState === "open" ? "closed" : "open";

        await expect(reasoningContent).toHaveAttribute(
          "data-state",
          nextState
        );
      },
      async upvote() {
        const voteAwaiter = self.waitForVoteRequest("up");
        self.pendingVoteRequest = voteAwaiter;
        await Promise.all([
          voteAwaiter.catch(() => {
            /* handled in isVoteComplete */
          }),
          lastMessageElement.getByTestId("message-upvote").click(),
        ]);
      },
      async downvote() {
        const voteAwaiter = self.waitForVoteRequest("down");
        self.pendingVoteRequest = voteAwaiter;
        await Promise.all([
          voteAwaiter.catch(() => {
            /* handled in isVoteComplete */
          }),
          lastMessageElement.getByTestId("message-downvote").click(),
        ]);
      },
    };
  }

  async getRecentUserMessage() {
    const messageElements = await this.page.getByTestId("message-user").all();
    const lastMessageElement = messageElements.at(-1);

    if (!lastMessageElement) {
      throw new Error("No user message found");
    }

    const content = await lastMessageElement
      .getByTestId("message-content")
      .innerText()
      .then((value) => value?.trim() ?? "")
      .catch(() => "");

    const hasAttachments = await lastMessageElement
      .getByTestId("message-attachments")
      .isVisible()
      .catch(() => false);

    const attachments = hasAttachments
      ? await lastMessageElement.getByTestId("message-attachments").all()
      : [];

    const page = this.page;
    const waitForChatApiResponse = this.waitForChatApiResponse.bind(this);
    const self = this;

    return {
      element: lastMessageElement,
      content,
      attachments,
      async edit(newMessage: string) {
        await page.getByTestId("message-edit-button").click();
        await page.getByTestId("message-editor").fill(newMessage);
        /**
         * Editing often happens after the tester scrolls through history. Make
         * sure the viewport is anchored to the latest messages so the inline
         * editor’s send button is visible and Playwright doesn’t have to fight
         * with the floating “scroll to bottom” control.
         */
        await self.waitForScrollToBottom().catch(() => {});
        await self.prepareForGeneration();
        await Promise.all([
          waitForChatApiResponse(),
          page.getByTestId("message-editor-send-button").click(),
        ]);
        await page
          .getByTestId("message-editor-send-button")
          .waitFor({ state: "hidden" })
          .catch(async () => {
            /**
             * Some transports remove the editor from the DOM entirely instead of
             * hiding the send button. Falling back to `detached` keeps the
             * helper resilient across UI refactors while still guaranteeing the
             * edit cycle finished.
             */
            await page
              .getByTestId("message-editor-send-button")
              .waitFor({ state: "detached" });
          });
      },
    };
  }

  /**
   * Capture the current assistant state before dispatching a new user action so
   * `isGenerationComplete` can later diff the DOM against a stable baseline.
   * This keeps the polling logic deterministic across synchronous mocks and
   * long-running finance tool chains.
   */
  private async prepareForGeneration(): Promise<void> {
    this.pendingAssistantSnapshot = await this.captureAssistantSnapshot();
    this.pendingUserMessageCount = await this.page
      .getByTestId("message-user")
      .count()
      .catch(() => 0);
    this.pendingStopButtonWasVisible = await this.stopButton
      .isVisible()
      .catch(() => false);
    this.pendingSendButtonWasVisible = await this.sendButton
      .isVisible()
      .catch(() => false);
    this.pendingSendButtonWasEnabled = await this.sendButton
      .isEnabled()
      .catch(() => false);
  }

  private async waitForComposerReady(
    message: string,
    options?: { timeout?: number; pollInterval?: number }
  ): Promise<void> {
    const timeout = options?.timeout ?? 30_000;
    const pollInterval = options?.pollInterval ?? 100;
    const deadline = Date.now() + timeout;

    const composer = this.multimodalInput;
    const sendButton = this.sendButton;
    const stopButton = this.stopButton;

    // Give the controlled textarea focus and seed the outbound prompt exactly
    // as a user would: clear any residue and type the message character by
    // character so React receives the full cascade of keyboard events.
    await composer.click();
    await composer.fill("");
    await composer.type(message);

    let lastComposerValue = "";
    let lastSendEnabled = false;
    let stopVisible = false;

    while (Date.now() < deadline) {
      [lastComposerValue, lastSendEnabled, stopVisible] = await Promise.all([
        composer.inputValue().catch(() => ""),
        sendButton.isEnabled().catch(() => false),
        stopButton.isVisible().catch(() => false),
      ]);

      if (lastComposerValue === message && lastSendEnabled && !stopVisible) {
        return;
      }

      // Hydration occasionally replaces the textarea node, wiping the value in
      // the process. When that happens, re-seed the input so the composer state
      // matches the outbound message and Playwright does not submit an empty
      // payload.
      if (lastComposerValue !== message) {
        await composer.fill("");
        await composer.type(message);
      }

      const remaining = Math.max(0, deadline - Date.now());
      await this.page.waitForTimeout(Math.min(pollInterval, remaining));
    }

    const composerDiagnostic =
      lastComposerValue.trim().length > 0
        ? ` Composer retained value: "${lastComposerValue}".`
        : " Composer remained empty.";
    const sendDiagnostic = lastSendEnabled ? "" : " Send button stayed disabled.";
    const stopDiagnostic = stopVisible
      ? " Stop button remained visible, indicating an active stream."
      : "";

    throw new Error(
      "Composer never became ready before submission." +
        composerDiagnostic +
        sendDiagnostic +
        stopDiagnostic
    );
  }

  private async captureAssistantSnapshot(): Promise<AssistantSnapshot> {
    const assistantMessages = this.page.getByTestId("message-assistant");
    const count = await assistantMessages.count();

    if (count === 0) {
      return {
        count,
        latestArtifactCount: 0,
        latestMessageId: null,
        latestMessageText: "",
      };
    }

    const latestAssistant = assistantMessages.nth(count - 1);
    const latestMessageId = await latestAssistant
      .getAttribute("data-message-id")
      .catch(() => null);
    const latestMessageText = await latestAssistant
      .getByTestId("message-content")
      .innerText()
      .then((value) => value.trim())
      .catch(() => "");
    const latestArtifactCount = await latestAssistant
      .locator('[data-testid$="-artifact"]')
      .count()
      .catch(() => 0);

    return {
      count,
      latestArtifactCount,
      latestMessageId,
      latestMessageText,
    };
  }

  /**
   * Determine whether a Playwright network primitive represents a chat API
   * request. The helper intentionally accepts both `Request` objects (emitted
   * by the `requestfailed` event) and `Response.request()` handles so the
   * matching logic stays centralised and less error-prone.
   */
  private matchesChatApiRequest(
    candidate:
      | { url: () => string; method: () => string }
      | undefined
      | null
  ): candidate is { url: () => string; method: () => string } {
    if (!candidate) {
      return false;
    }

    if (typeof candidate.url !== "function") {
      return false;
    }

    const method =
      typeof candidate.method === "function" ? candidate.method() : null;
    const normalizedMethod = method?.toUpperCase() ?? null;

    const rawUrl = candidate.url();
    
    try {
      const { pathname } = new URL(rawUrl);

      const isStreamPath = CHAT_STREAM_PATH_REGEX.test(pathname);
      const isChatRoot = pathname === "/api/chat";

      if (!isChatRoot && !isStreamPath) {
        return false;
      }

      if (!normalizedMethod) {
        return true;
      }

      if (["POST", "PATCH", "PUT"].includes(normalizedMethod)) {
        return true;
      }

      if (normalizedMethod === "GET") {
        /**
         * The Vercel AI SDK resumes Server-Sent Event streams via
         * `GET /api/chat/:id/stream`. Accept the read transport so suggestion
         * helpers observe the streaming hook without waiting for UI fallbacks.
         */
        return isStreamPath;
      }

      return false;
    } catch {
      /**
       * Unit tests occasionally stub the Playwright request object with bare
       * relative URLs. Falling back to a substring check keeps the predicate
       * permissive for those scenarios while the production code continues to
       * rely on full URL parsing.
       */
      const includesChatPath = rawUrl.includes("/api/chat");
      const includesStreamSegment = rawUrl.includes("/stream");

      if (!includesChatPath) {
        return false;
      }

      if (!normalizedMethod) {
        return true;
      }

      if (["POST", "PATCH", "PUT"].includes(normalizedMethod)) {
        return true;
      }

      if (normalizedMethod === "GET") {
        return includesStreamSegment;
      }

      return false;
    }
  }

  private async waitForChatApiResponse(): Promise<void> {
    /**
     * Prefer detecting the transport via Playwright's network events so we
     * surface HTTP failures immediately. If the browser driver does not emit
     * the expected hooks (Playwright regressions, streaming nuances, etc.), we
     * fall back to observing the chat UI so the helper still unblocks once the
     * stop button appears.
     */
    const networkTimeoutMarker = Symbol("chat-network-timeout");
    const networkTimeoutMs = 15_000;
    const uiFallbackTimeoutMs = 45_000;

    try {
      await new Promise<void>((resolve, reject) => {
        const page = this.page;
        const browserContext = page.context?.();
        /**
         * Network activity triggered by Playwright fixtures can originate from
         * either the page itself (UI-driven fetches) or the enclosing browser
         * context (APIRequestContext helpers). Observing both emitters ensures
         * the guard reacts to transports initiated during hermetic setup,
         * including the quick-action flows exercised by the CI suite.
         */
        const eventTargets: Array<{
          on: (event: string, listener: (...args: unknown[]) => void) => void;
          off: (event: string, listener: (...args: unknown[]) => void) => void;
        }> = [page as any];

        if (
          browserContext &&
          typeof (browserContext as { on?: unknown }).on === "function" &&
          typeof (browserContext as { off?: unknown }).off === "function"
        ) {
          eventTargets.push(browserContext as any);
        }

        let settled = false;
        let timer: ReturnType<typeof setTimeout>;
        let sawMatchingRequest = false;

        const cleanup = () => {
          clearTimeout(timer);
          for (const target of eventTargets) {
            target.off("request", handleRequest);
            target.off("response", handleResponse);
            target.off("requestfailed", handleFailure);
          }
        };

        const settle = (result: "resolve" | "reject", reason?: unknown) => {
          if (settled) {
            return;
          }

          settled = true;
          cleanup();

          if (result === "resolve") {
            resolve();
          } else {
            reject(reason);
          }
        };

        const handleRequest = (request: unknown) => {
          if (!this.matchesChatApiRequest(request as any)) {
            return;
          }

          sawMatchingRequest = true;
        };

        const handleResponse = async (response: unknown) => {
          const candidate =
            typeof response === "object" &&
            response !== null &&
            "request" in response
              ? (response as any).request()
              : null;

          if (!this.matchesChatApiRequest(candidate)) {
            return;
          }

          try {
            if (!(response as any).ok()) {
              let bodySnippet = "";

              try {
                bodySnippet = await (response as any).text();
              } catch {
                bodySnippet = "";
              }

              const trimmedBody = bodySnippet.trim().slice(0, 1_000);
              const diagnostic =
                trimmedBody.length > 0 ? ` – ${trimmedBody}` : "";

              settle(
                "reject",
                new Error(
                  `Chat API request failed with ${(response as any).status()} ${(response as any).statusText()}${diagnostic}`
                )
              );
              return;
            }

            settle("resolve");
          } catch (error) {
            settle(
              "reject",
              error instanceof Error
                ? error
                : new Error("Chat API response handling failed")
            );
          }
        };

        const handleFailure = async (request: unknown) => {
          const candidate = request as any;

          if (!this.matchesChatApiRequest(candidate)) {
            return;
          }

          let diagnostic = "";
          let normalizedDiagnostic = "";
          try {
            // Normalise Playwright's optional `failure()` accessor so the
            // helper can surface the original network error text without
            // tripping strict type checks in the Vitest environment.
            const failureFn =
              candidate &&
              typeof candidate === "object" &&
              "failure" in candidate &&
              typeof (candidate as { failure?: unknown }).failure === "function"
                ? (candidate as { failure: () => unknown }).failure
                : null;

            const failureDetails = await Promise.resolve(
              failureFn ? failureFn() : null
            );
            // Some runtimes expose richer error payloads (Chromium) while
            // others only emit bare network codes. Gate access through a
            // structural check so we stay compatible everywhere.
            const failureText =
              failureDetails &&
              typeof failureDetails === "object" &&
              "errorText" in failureDetails &&
              typeof (failureDetails as { errorText?: unknown }).errorText ===
                "string"
                ? (failureDetails as { errorText: string }).errorText.trim()
                : "";
            diagnostic = failureText ? ` – ${failureText}` : "";
            normalizedDiagnostic = failureText.toUpperCase();
          } catch {
            diagnostic = "";
            normalizedDiagnostic = "";
          }

          // Offline Playwright runs may surface ENETUNREACH/ERR_NETWORK_* when
          // Chromium blocks requests to the hermetic Next.js server while it is
          // still compiling. Treat those as soft failures so we can fall back to
          // DOM-based polling instead of failing the scenario outright.
          const offlineFailureSignals = [
            "ENETUNREACH",
            "ERR_NETWORK_CHANGED",
            "ERR_INTERNET_DISCONNECTED",
            "ERR_NETWORK_IO_SUSPENDED",
            "ERR_CONNECTION_REFUSED",
            "ERR_CONNECTION_RESET",
            "ERR_ADDRESS_UNREACHABLE",
          ];

          if (
            offlineFailureSignals.some((signal) =>
              normalizedDiagnostic.includes(signal)
            )
          ) {
            console.warn(
              "Chat API network request failed in offline mode; falling back to UI polling.",
              {
                failure:
                  diagnostic.length > 0
                    ? diagnostic.trim().replace(/^–\s*/, "")
                    : offlineFailureSignals.find((signal) =>
                        normalizedDiagnostic.includes(signal)
                      ),
                url:
                  typeof candidate?.url === "function"
                    ? candidate.url()
                    : undefined,
              }
            );

            settle("reject", networkTimeoutMarker);
            return;
          }

          settle(
            "reject",
            new Error(
              `Chat API request failed before receiving a response${diagnostic}`
            )
          );
        };

        timer = setTimeout(() => {
          if (sawMatchingRequest) {
            settle("resolve");
            return;
          }

          settle("reject", networkTimeoutMarker);
        }, networkTimeoutMs);

        for (const target of eventTargets) {
          target.on("request", handleRequest);
          target.on("response", handleResponse);
          target.on("requestfailed", handleFailure);
        }
      });

      return;
    } catch (error) {
      if (error !== networkTimeoutMarker) {
        throw error instanceof Error
          ? error
          : new Error("Chat API request failed");
      }
    }

    const baselineSnapshot =
      this.pendingAssistantSnapshot ??
      (await this.captureAssistantSnapshot());

    await this.waitForUiStreamingFallback({
      baseline: baselineSnapshot,
      baselineUserMessageCount: this.pendingUserMessageCount,
      baselineStopButtonVisible: this.pendingStopButtonWasVisible,
      baselineSendButtonVisible: this.pendingSendButtonWasVisible,
      baselineSendButtonEnabled: this.pendingSendButtonWasEnabled,
      timeoutMs: uiFallbackTimeoutMs,
    });
  }

  private async waitForUiStreamingFallback({
    baseline,
    baselineUserMessageCount,
    baselineStopButtonVisible,
    baselineSendButtonVisible,
    baselineSendButtonEnabled,
    timeoutMs,
  }: {
    baseline: AssistantSnapshot;
    baselineUserMessageCount: number;
    baselineStopButtonVisible: boolean;
    baselineSendButtonVisible: boolean;
    baselineSendButtonEnabled: boolean;
    timeoutMs: number;
  }): Promise<void> {
    const toast = this.page.locator(TOAST_LOCATOR).first();

    const rawToastPromise = toast
      .waitFor({ state: "visible", timeout: timeoutMs })
      .then(async () => {
        const description = await toast
          .innerText()
          .then((value) => value.trim())
          .catch(() => "");

        const suffix = description.length > 0 ? `: ${description}` : "";
        throw new Error(`Chat UI reported an error toast${suffix}`);
      });
    const toastPromise = rawToastPromise.catch((error) => {
      throw error;
    });

    const streamingPromise = this.pollForStreamingChange({
      baseline,
      baselineUserMessageCount,
      baselineStopButtonVisible,
      baselineSendButtonVisible,
      baselineSendButtonEnabled,
      timeoutMs,
    });

    try {
      await Promise.race([toastPromise, streamingPromise]);
    } catch (error) {
      if (isTimeoutLikeError(error)) {
        throw new Error("Timed out waiting for chat UI to start streaming");
      }
      throw error;
    } finally {
      rawToastPromise.catch(() => {});
      streamingPromise.catch(() => {});
    }
  }

  private async resolveModelSelectorItem({
    chatModel,
    timeoutMs,
  }: {
    chatModel: ChatModel;
    timeoutMs: number;
  }): Promise<Locator> {
    const deadline = Date.now() + timeoutMs;
    const testIdLocator = this.page.getByTestId(
      `model-selector-item-${chatModel.id}`
    );
    const optionLocator = this.page
      .getByRole("option", { name: chatModel.name })
      .first();
    const menuItemLocator = this.page
      .getByRole("menuitem", { name: chatModel.name })
      .first();

    while (Date.now() < deadline) {
      if ((await testIdLocator.count().catch(() => 0)) > 0) {
        return testIdLocator.first();
      }

      if ((await optionLocator.count().catch(() => 0)) > 0) {
        return optionLocator;
      }

      if ((await menuItemLocator.count().catch(() => 0)) > 0) {
        return menuItemLocator;
      }

      await this.page.waitForTimeout(100);
    }

    throw new Error(
      `Unable to locate the model selector option for "${chatModel.name}".`
    );
  }

  private async pollForStreamingChange({
    baseline,
    baselineUserMessageCount,
    baselineStopButtonVisible,
    baselineSendButtonVisible,
    baselineSendButtonEnabled,
    timeoutMs,
  }: {
    baseline: AssistantSnapshot;
    baselineUserMessageCount: number;
    baselineStopButtonVisible: boolean;
    baselineSendButtonVisible: boolean;
    baselineSendButtonEnabled: boolean;
    timeoutMs: number;
  }): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    const assistantLocator = this.page.getByTestId("message-assistant");
    const userLocator = this.page.getByTestId("message-user");
    const spinnerLocator = this.page.getByTestId("message-assistant-loading");
    const stopButtonLocator = this.stopButton;
    const sendButtonLocator = this.sendButton;
    let hasObservedStopButtonHidden = !baselineStopButtonVisible;
    let hasObservedSendButtonVisible = baselineSendButtonVisible;
    let hasObservedSendButtonEnabled = baselineSendButtonEnabled;

    while (Date.now() < deadline) {
      const [
        assistantCount,
        spinnerCount,
        stopVisible,
        sendVisible,
        sendEnabled,
        userCount,
      ] = await Promise.all([
        assistantLocator.count().catch(() => 0),
        spinnerLocator.count().catch(() => 0),
        stopButtonLocator.isVisible().catch(() => false),
        sendButtonLocator.isVisible().catch(() => false),
        sendButtonLocator.isEnabled().catch(() => false),
        userLocator.count().catch(() => 0),
      ]);

      if (spinnerCount > 0) {
        return;
      }

      if (!sendVisible) {
        if (hasObservedSendButtonVisible) {
          return;
        }
      } else {
        if (!hasObservedSendButtonVisible) {
          hasObservedSendButtonVisible = true;
        }

        if (!sendEnabled && hasObservedSendButtonEnabled) {
          return;
        }

        if (sendEnabled && !hasObservedSendButtonEnabled) {
          hasObservedSendButtonEnabled = true;
        }
      }

      if (stopVisible) {
        if (!baselineStopButtonVisible) {
          return;
        }

        if (hasObservedStopButtonHidden) {
          return;
        }
      } else if (baselineStopButtonVisible && !hasObservedStopButtonHidden) {
        hasObservedStopButtonHidden = true;
      }

      if (userCount > baselineUserMessageCount) {
        return;
      }

      if (assistantCount > baseline.count) {
        return;
      }

      if (assistantCount > 0) {
        const latestAssistant = assistantLocator.nth(assistantCount - 1);
        const [latestId, latestText, latestArtifactCount] = await Promise.all([
          latestAssistant.getAttribute("data-message-id").catch(() => null),
          latestAssistant
            .getByTestId("message-content")
            .innerText()
            .then((value) => value.trim())
            .catch(() => ""),
          latestAssistant
            .locator('[data-testid$="-artifact"]')
            .count()
            .catch(() => 0),
        ]);

        if (latestId && latestId !== baseline.latestMessageId) {
          return;
        }

        if (latestText && latestText !== baseline.latestMessageText) {
          return;
        }

        if (latestArtifactCount > baseline.latestArtifactCount) {
          return;
        }
      }

      await this.page.waitForTimeout(200);
    }

    throw new Error("Timed out waiting for chat UI to start streaming");
  }

  private async waitForVoteRequest(direction: "up" | "down"): Promise<void> {
    const response = await this.page.waitForResponse((candidate) => {
      const request = candidate.request();
      if (!request || request.method() !== "PATCH") {
        return false;
      }

      const rawUrl = candidate.url();
      try {
        const { pathname } = new URL(rawUrl);
        if (pathname !== "/api/vote") {
          return false;
        }
      } catch {
        if (!rawUrl.includes("/api/vote")) {
          return false;
        }
      }

      try {
        const parse =
          typeof request.postDataJSON === "function"
            ? request.postDataJSON.bind(request)
            : null;
        const body = parse ? parse() : {};
        return body?.type === direction;
      } catch {
        return true;
      }
    }, { timeout: 15_000 });

    if (!response.ok()) {
      const status = response.status();
      const statusText = response.statusText();
      throw new Error(
        `Vote request failed with ${status} ${statusText}`
      );
    }
  }
  async expectToastToContain(text: string) {
    await expect(this.page.locator(TOAST_LOCATOR).first()).toContainText(text);
  }

  async openSideBar() {
    const sidebarToggleButton = this.page.getByTestId("sidebar-toggle-button");
    await sidebarToggleButton.click();
  }

  isScrolledToBottom(): Promise<boolean> {
    return this.scrollContainer.evaluate(
      (el) => Math.abs(el.scrollHeight - el.scrollTop - el.clientHeight) < 1
    );
  }

  async waitForScrollToBottom(timeout = 5000): Promise<void> {
    const start = Date.now();

    while (Date.now() - start < timeout) {
      if (await this.isScrolledToBottom()) {
        return;
      }
      await this.page.waitForTimeout(100);
    }

    throw new Error(`Timed out waiting for scroll bottom after ${timeout}ms`);
  }

  async sendMultipleMessages(
    count: number,
    makeMessage: (i: number) => string
  ) {
    for (let i = 0; i < count; i++) {
      await this.sendUserMessage(makeMessage(i));
      await this.isGenerationComplete();
    }
  }

  async scrollToTop(): Promise<void> {
    await this.scrollContainer.evaluate((element) => {
      element.scrollTo({ top: 0, behavior: "auto" });
      /**
       * Programmatic scrolls in Playwright do not always emit the `scroll`
       * event, which means React’s listeners would miss the state change and
       * keep the "scroll to bottom" button hidden. Dispatch the event manually
       * so the UI mirrors a real user interaction.
       */
      element.dispatchEvent(new Event("scroll"));
    });
  }
}

function isTimeoutLikeError(error: unknown): boolean {
  if (!error) {
    return false;
  }

  if (error instanceof playwrightErrors.TimeoutError) {
    return true;
  }

  if (error instanceof Error) {
    if (error.name === "TimeoutError") {
      return true;
    }

    return error.message.toLowerCase().includes("timeout");
  }

  return false;
}
