import fs from "node:fs";
import path from "node:path";
import { expect, type Page, errors as playwrightErrors } from "@playwright/test";
import { chatModels } from "@/lib/ai/models";

/**
 * Validate that the current page URL ends with a chat identifier without
 * coupling the assertion to a specific host or port. Playwright drives the app
 * on a dynamic base URL (port 3000 locally, 3100 during hermetic runs), so we
 * only assert on the `/chat/:id` suffix. The UUID shape mirrors the database
 * identifiers generated by Drizzle.
 */
const CHAT_ID_REGEX = /\/chat\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

/**
 * Streaming requests reuse the chat API namespace but append the chat
 * identifier before `/stream`. We match both the base route and streaming
 * suffix so the helper recognises edits and retries as well as brand new
 * chats, regardless of the query string Playwright attaches when retrying.
 */
const CHAT_STREAM_PATH_REGEX = /^\/api\/chat\/[\w-]+\/stream$/;

export class ChatPage {
  /**
   * Surface the Playwright assertion helper so unit tests can substitute a
   * lightweight spy without mutating the imported module namespace.
   */
  static expect = expect;

  private readonly page: Page;

  /**
   * Snapshot of the assistant timeline captured right before triggering a new
   * generation. We compare the stored baseline with the live DOM while polling
   * so the helper recognises both brand-new bubbles and updates to the latest
   * message content or attached artefacts.
   */
  private pendingAssistantSnapshot:
    | {
        count: number;
        latestMessageId: string | null;
        latestMessageText: string;
        latestArtifactCount: number;
      }
    | null = null;

  /**
   * Track the most recent vote request so the helper can await the matching
   * `/api/vote` response and avoid relying solely on transient UI signals.
   */
  private pendingVoteRequest: Promise<void> | null = null;

  constructor(page: Page) {
    this.page = page;
  }

  get sendButton() {
    return this.page.getByTestId("send-button");
  }

  get stopButton() {
    return this.page.getByTestId("stop-button");
  }

  get multimodalInput() {
    return this.page.getByTestId("multimodal-input");
  }

  get scrollContainer() {
    return this.page.locator(".overflow-y-scroll");
  }

  get scrollToBottomButton() {
    return this.page.getByTestId("scroll-to-bottom-button");
  }

  async createNewChat() {
    await this.page.goto("/", {
      /**
       * Next.js app router streams the shell before every asset finishes
       * loading, which occasionally blocks the `load` event during cold Turbopack
       * starts. Waiting for `domcontentloaded` keeps the navigation resilient in
       * hermetic Playwright runs without masking legitimate network hangs.
       */
      waitUntil: "domcontentloaded",
    });
  }

  getCurrentURL(): string {
    return this.page.url();
  }

  async sendUserMessage(message: string) {
    await this.multimodalInput.click();
    await this.multimodalInput.fill(message);

    await this.prepareForGeneration();

    /**
     * Trigger the send action and the API wait concurrently so we capture the
     * network response associated with this submission. Surfacing transport
     * failures immediately makes the suite easier to debug than waiting for the
     * streaming assertions to eventually time out.
     */
    await Promise.all([
      this.waitForChatApiResponse(),
      this.sendButton.click(),
    ]);
  }

  async isGenerationComplete() {
    const assistantMessages = this.page.getByTestId("message-assistant");
    const {
      count: initialAssistantCount,
      latestMessageId: initialLatestMessageId,
      latestMessageText: initialLatestMessage,
      latestArtifactCount: initialArtifactCount,
    } =
      this.pendingAssistantSnapshot ??
      (await this.captureAssistantSnapshot());

    this.pendingAssistantSnapshot = null;
    /**
     * Finance journeys often render artefacts (chart, backtest, news) without
     * adding textual content to the assistant bubble. Tracking the initial
     * artefact footprint lets us confirm the UI updated even when the message
     * copy stays empty – a scenario that previously caused the polling loop to
     * spin forever and eventually time out the Playwright run.
     */

    /**
     * Some chat journeys (notably the finance accessibility sweep) reuse the
     * same assistant bubble when multiple prompts run back to back. The DOM
     * still streams fresh content, but the overall assistant count remains
     * stable. Poll both the count and the text payload so we unblock as soon as
     * either a new bubble appears or the latest response finishes streaming.
     */
    await this.page.waitForFunction(
      (args: {
        initialAssistantCount: number;
        initialLatestMessageId: string | null;
        initialLatestMessage: string;
        initialArtifactCount: number;
      }) => {
        const {
          initialAssistantCount,
          initialLatestMessageId,
          initialLatestMessage,
          initialArtifactCount,
        } = args;

        const toast = document.querySelector<HTMLElement>('[data-testid="toast"]');
        const toastText = toast?.textContent?.trim() ?? '';
        if (toastText.length > 0) {
          throw new Error(
            `Chat surfaced an error toast while waiting for the assistant response: ${toastText}`
          );
        }

        const assistantNodes = Array.from(
          document.querySelectorAll<HTMLElement>('[data-testid="message-assistant"]')
        );
        const currentCount = assistantNodes.length;

        if (currentCount > initialAssistantCount) {
          return true;
        }

        if (currentCount === initialAssistantCount && currentCount > 0) {
          const latestAssistant = assistantNodes[currentCount - 1];
          const latestMessageId = latestAssistant.getAttribute('data-message-id');

          if (latestMessageId && latestMessageId !== initialLatestMessageId) {
            return true;
          }

          const latestContent =
            latestAssistant
              .querySelector<HTMLElement>('[data-testid="message-content"]')
              ?.innerText.trim() ?? '';

          if (latestContent.length > 0 && latestContent !== initialLatestMessage) {
            return true;
          }

          const latestArtifactCount = latestAssistant.querySelectorAll('[data-testid$="-artifact"]').length;

          if (latestArtifactCount > initialArtifactCount) {
            return true;
          }

          const loadingCount = document.querySelectorAll('[data-testid="message-assistant-loading"]').length;
          const stopButton = document.querySelector<HTMLElement>('[data-testid="stop-button"]');
          const stopVisible =
            !!stopButton &&
            stopButton.offsetParent !== null &&
            window.getComputedStyle(stopButton).visibility !== 'hidden';

          if (stopVisible) {
            /**
             * Inline edit submissions reuse the global composer state. When the
             * stop button is visible we know the chat helpers started
             * streaming, so the fallback can return immediately without
             * waiting for additional DOM signals.
             */
            return true;
          }

          if (loadingCount === 0 && !stopVisible) {
            return true;
          }
        }

        return false;
      },
      {
        initialAssistantCount,
        initialLatestMessageId,
        initialLatestMessage,
        initialArtifactCount,
      },
      { timeout: 60_000 }
    );

    /**
     * The assistant stream reuses the same container while piping tool results
     * into the UI. By the time we reach this section the guard above has either
     * observed a brand-new bubble or detected fresh content within the latest
     * one, so selecting `count() - 1` safely targets the resolved response even
     * when earlier interactions left history entries in the DOM.
     */

    const latestAssistantMessage = assistantMessages.nth(
      (await assistantMessages.count()) - 1
    );
    await latestAssistantMessage.waitFor({ state: "attached" });

    await expect(this.page.getByTestId("message-assistant-loading")).toHaveCount(0);
    await expect(this.page.getByTestId("stop-button")).toHaveCount(0);

    const sendButton = this.sendButton;
    await expect(sendButton).toBeVisible();

    const latestMessageContent = latestAssistantMessage.getByTestId(
      "message-content"
    );

    let previousText = "";
    let stableIterations = 0;

    for (let attempt = 0; attempt < 50; attempt++) {
      const currentText = (await latestMessageContent.innerText()).trim();

      if (currentText && currentText === previousText) {
        stableIterations += 1;
        if (stableIterations >= 2) {
          break;
        }
      } else {
        stableIterations = 0;
        previousText = currentText;
      }

      await this.page.waitForTimeout(200);
    }

    const [finalText, finalArtifactCount] = await Promise.all([
      latestMessageContent.innerText().then((value) => value.trim()),
      latestAssistantMessage
        .locator('[data-testid$="-artifact"]')
        .count()
        .catch(() => 0),
    ]);

    /**
     * Artefact-only responses intentionally leave the chat bubble empty while
     * rendering dedicated finance components. Accept either textual deltas or
     * newly attached artefacts so both interaction styles satisfy the
     * completion contract.
     */
    expect(finalText.length > 0 || finalArtifactCount > 0).toBe(true);
  }

  async isVoteComplete(direction: "up" | "down" = "up") {
    /**
     * Voting triggers a toast notification via `toast.promise`. Waiting on the
     * visual feedback keeps the helper independent from the underlying fetch
     * request so the e2e suite remains hermetic and does not rely on network
     * responses resolving.
     */
    const voteButton = this.page.getByTestId(
      direction === "up" ? "message-upvote" : "message-downvote"
    );

    const toast = this.page.getByTestId("toast");
    const successCopy =
      direction === "up" ? "Upvoted Response!" : "Downvoted Response!";

    /**
     * Sonner silently drops toast updates when another notification is already
     * visible. Rather than timing out the suite when the success toast never
     * renders, attempt to observe it with a short grace period and fall back to
     * the button state if the toast is skipped.
     */
    const toastAppeared = await toast
      .waitFor({ state: "visible", timeout: 2_000 })
      .then(() => true)
      .catch(() => false);

    if (toastAppeared) {
      await ChatPage.expect(toast).toContainText(successCopy);
    }

    if (this.pendingVoteRequest) {
      try {
        await this.pendingVoteRequest;
      } finally {
        this.pendingVoteRequest = null;
      }
    }

    /**
     * SWR mutates the cached vote state in the background. Give the UI a few
     * moments to reflect the disabled state locally before falling back to the
     * optimistic network confirmation above.
     */
    const disableDeadline = Date.now() + 10_000;
    while (Date.now() < disableDeadline) {
      if (await voteButton.isDisabled()) {
        return;
      }

      await this.page.waitForTimeout(200);
    }
  }

  async hasChatIdInUrl() {
    await expect(this.page).toHaveURL(CHAT_ID_REGEX);
  }

  async sendUserMessageFromSuggestion() {
    /**
     * Target the deterministic suggestion test identifier so the helper keeps
     * working even when the rendered label changes (for example due to
     * different font fallbacks in offline Playwright runs).
     */
    await this.prepareForGeneration();

    await Promise.all([
      this.waitForChatApiResponse(),
      this.page.getByTestId("suggested-action-0").click(),
    ]);
  }

  async isElementVisible(elementId: string) {
    await expect(this.page.getByTestId(elementId)).toBeVisible();
  }

  async isElementNotVisible(elementId: string) {
    await expect(this.page.getByTestId(elementId)).not.toBeVisible();
  }

  async addImageAttachment() {
    const attachmentsButton = this.page.getByTestId("attachments-button");

    /**
     * Reasoning models disable file uploads in the composer. When the current
     * chat session uses that model, temporarily switch back to the default
     * conversational model so the attachment preview renders just like it does
     * in production. This mirrors the behaviour a user would follow manually
     * and keeps the Playwright journey deterministic.
     */
    if (await attachmentsButton.isDisabled()) {
      const fallbackModel =
        chatModels.find((model) => model.id === "chat-model") ?? chatModels[0];

      if (!fallbackModel) {
        throw new Error("Unable to determine the default chat model");
      }

      await this.chooseModelFromSelector(fallbackModel.id);
      await expect(attachmentsButton).toBeEnabled();
    }

    this.page.on("filechooser", async (fileChooser) => {
      const filePath = path.join(
        process.cwd(),
        "public",
        "images",
        "mouth of the seine, monet.jpg"
      );
      const imageBuffer = fs.readFileSync(filePath);

      await fileChooser.setFiles({
        name: "mouth of the seine, monet.jpg",
        mimeType: "image/jpeg",
        buffer: imageBuffer,
      });
    });

    await attachmentsButton.click();
  }

  async getSelectedModel() {
    const modelId = await this.page.getByTestId("model-selector").innerText();
    return modelId;
  }

  async chooseModelFromSelector(chatModelId: string) {
    const chatModel = chatModels.find(
      (currentChatModel) => currentChatModel.id === chatModelId
    );

    if (!chatModel) {
      throw new Error(`Model with id ${chatModelId} not found`);
    }

    const selectorTrigger = this.page.getByTestId("model-selector");

    // Wait for the selector trigger to hydrate before attempting to interact.
    await expect(selectorTrigger).toBeVisible({ timeout: 60_000 });
    await expect(selectorTrigger).toBeEnabled();

    await selectorTrigger.click();

    const selectorItem = this.page.getByTestId(
      `model-selector-item-${chatModelId}`
    );

    await expect(selectorItem).toBeVisible({ timeout: 60_000 });
    await selectorItem.click();

    expect(await this.getSelectedModel()).toBe(chatModel.name);
  }

  async getSelectedVisibility() {
    const visibilityId = await this.page
      .getByTestId("visibility-selector")
      .innerText();
    return visibilityId;
  }

  async chooseVisibilityFromSelector(chatVisibility: "public" | "private") {
    await this.page.getByTestId("visibility-selector").click();
    await this.page
      .getByTestId(`visibility-selector-item-${chatVisibility}`)
      .click();
    expect(await this.getSelectedVisibility()).toBe(chatVisibility);
  }

  async getRecentAssistantMessage() {
    const messageElements = await this.page
      .getByTestId("message-assistant")
      .all();
    const lastMessageElement = messageElements.at(-1);

    if (!lastMessageElement) {
      throw new Error("No assistant message found");
    }

    const content = await lastMessageElement
      .getByTestId("message-content")
      .innerText()
      .then((value) => value?.trim() ?? "")
      .catch(() => "");

    const reasoningContainer = lastMessageElement.getByTestId(
      "message-reasoning"
    );
    const reasoningTrigger = lastMessageElement.getByTestId(
      "message-reasoning-trigger"
    );
    const reasoningContent = lastMessageElement.getByTestId(
      "message-reasoning-content"
    );

    const reasoningText = await reasoningContent
      .waitFor({ state: "attached", timeout: 5_000 })
      .then(async () => {
        const isVisible = await reasoningContent
          .isVisible()
          .catch(() => false);

        if (!isVisible) {
          // Auto-close animations hide the reasoning snippet almost
          // immediately after streaming finishes. Re-open the accordion so we
          // can capture the full explanation before returning it to callers.
          await reasoningTrigger.click();
          await reasoningContent.waitFor({ state: "visible", timeout: 5_000 });
        }

        return reasoningContent
          .innerText()
          .then((value) => value?.trim() ?? "")
          .catch(() => null);
      })
      .catch(() => null);

    const self = this;

    return {
      element: lastMessageElement,
      content,
      reasoning: reasoningText,
      reasoningElement: reasoningContainer,
      async toggleReasoningVisibility() {
        const currentState = await reasoningContent
          .getAttribute("data-state")
          .catch(() => null);

        await reasoningTrigger.click();

        // Defensive guard: if the attribute is missing we bail out rather
        // than waiting forever on an assertion that would never settle.
        if (!currentState) {
          return;
        }

        const nextState = currentState === "open" ? "closed" : "open";

        await expect(reasoningContent).toHaveAttribute(
          "data-state",
          nextState
        );
      },
      async upvote() {
        const voteAwaiter = self.waitForVoteRequest("up");
        self.pendingVoteRequest = voteAwaiter;
        await Promise.all([
          voteAwaiter.catch(() => {
            /* handled in isVoteComplete */
          }),
          lastMessageElement.getByTestId("message-upvote").click(),
        ]);
      },
      async downvote() {
        const voteAwaiter = self.waitForVoteRequest("down");
        self.pendingVoteRequest = voteAwaiter;
        await Promise.all([
          voteAwaiter.catch(() => {
            /* handled in isVoteComplete */
          }),
          lastMessageElement.getByTestId("message-downvote").click(),
        ]);
      },
    };
  }

  async getRecentUserMessage() {
    const messageElements = await this.page.getByTestId("message-user").all();
    const lastMessageElement = messageElements.at(-1);

    if (!lastMessageElement) {
      throw new Error("No user message found");
    }

    const content = await lastMessageElement
      .getByTestId("message-content")
      .innerText()
      .then((value) => value?.trim() ?? "")
      .catch(() => "");

    const hasAttachments = await lastMessageElement
      .getByTestId("message-attachments")
      .isVisible()
      .catch(() => false);

    const attachments = hasAttachments
      ? await lastMessageElement.getByTestId("message-attachments").all()
      : [];

    const page = this.page;
    const waitForChatApiResponse = this.waitForChatApiResponse.bind(this);
    const self = this;

    return {
      element: lastMessageElement,
      content,
      attachments,
      async edit(newMessage: string) {
        await page.getByTestId("message-edit-button").click();
        await page.getByTestId("message-editor").fill(newMessage);
        /**
         * Editing often happens after the tester scrolls through history. Make
         * sure the viewport is anchored to the latest messages so the inline
         * editor’s send button is visible and Playwright doesn’t have to fight
         * with the floating “scroll to bottom” control.
         */
        await self.waitForScrollToBottom().catch(() => {});
        await self.prepareForGeneration();
        await Promise.all([
          waitForChatApiResponse(),
          page.getByTestId("message-editor-send-button").click(),
        ]);
        await page
          .getByTestId("message-editor-send-button")
          .waitFor({ state: "hidden" })
          .catch(async () => {
            /**
             * Some transports remove the editor from the DOM entirely instead of
             * hiding the send button. Falling back to `detached` keeps the
             * helper resilient across UI refactors while still guaranteeing the
             * edit cycle finished.
             */
            await page
              .getByTestId("message-editor-send-button")
              .waitFor({ state: "detached" });
          });
      },
    };
  }

  /**
   * Capture the current assistant state before dispatching a new user action so
   * `isGenerationComplete` can later diff the DOM against a stable baseline.
   * This keeps the polling logic deterministic across synchronous mocks and
   * long-running finance tool chains.
   */
  private async prepareForGeneration(): Promise<void> {
    this.pendingAssistantSnapshot = await this.captureAssistantSnapshot();
  }

  private async captureAssistantSnapshot(): Promise<
    NonNullable<typeof this.pendingAssistantSnapshot>
  > {
    const assistantMessages = this.page.getByTestId("message-assistant");
    const count = await assistantMessages.count();

    if (count === 0) {
      return {
        count,
        latestArtifactCount: 0,
        latestMessageId: null,
        latestMessageText: "",
      };
    }

    const latestAssistant = assistantMessages.nth(count - 1);
    const latestMessageId = await latestAssistant
      .getAttribute("data-message-id")
      .catch(() => null);
    const latestMessageText = await latestAssistant
      .getByTestId("message-content")
      .innerText()
      .then((value) => value.trim())
      .catch(() => "");
    const latestArtifactCount = await latestAssistant
      .locator('[data-testid$="-artifact"]')
      .count()
      .catch(() => 0);

    return {
      count,
      latestArtifactCount,
      latestMessageId,
      latestMessageText,
    };
  }

  /**
   * Determine whether a Playwright network primitive represents a chat API
   * request. The helper intentionally accepts both `Request` objects (emitted
   * by the `requestfailed` event) and `Response.request()` handles so the
   * matching logic stays centralised and less error-prone.
   */
  private matchesChatApiRequest(
    candidate:
      | { url: () => string; method: () => string }
      | undefined
      | null
  ): candidate is { url: () => string; method: () => string } {
    if (!candidate) {
      return false;
    }

    if (typeof candidate.method !== "function" || typeof candidate.url !== "function") {
      return false;
    }

    if (candidate.method() !== "POST") {
      return false;
    }

    const rawUrl = candidate.url();

    try {
      const { pathname } = new URL(rawUrl);

      if (pathname === "/api/chat") {
        return true;
      }

      return CHAT_STREAM_PATH_REGEX.test(pathname);
    } catch {
      /**
       * Unit tests occasionally stub the Playwright request object with bare
       * relative URLs. Falling back to a substring check keeps the predicate
       * permissive for those scenarios while the production code continues to
       * rely on full URL parsing.
       */
      return rawUrl.includes("/api/chat");
    }
  }

  private async waitForChatApiResponse(): Promise<void> {
    /**
     * Prefer detecting the transport via Playwright's network events so we
     * surface HTTP failures immediately. If the browser driver does not emit
     * the expected hooks (Playwright regressions, streaming nuances, etc.), we
     * fall back to observing the chat UI so the helper still unblocks once the
     * stop button appears.
     */
    const networkTimeoutMarker = Symbol("chat-network-timeout");
    const networkTimeoutMs = 5_000;
    const uiFallbackTimeoutMs = 45_000;

    try {
      await new Promise<void>((resolve, reject) => {
        const page = this.page;
        let settled = false;
        let timer: ReturnType<typeof setTimeout>;

        const cleanup = () => {
          clearTimeout(timer);
          page.off("response", handleResponse);
          page.off("requestfailed", handleFailure);
        };

        const settle = (result: "resolve" | "reject", reason?: unknown) => {
          if (settled) {
            return;
          }

          settled = true;
          cleanup();

          if (result === "resolve") {
            resolve();
          } else {
            reject(reason);
          }
        };

        const handleResponse = async (response: unknown) => {
          const candidate =
            typeof response === "object" &&
            response !== null &&
            "request" in response
              ? (response as any).request()
              : null;

          if (!this.matchesChatApiRequest(candidate)) {
            return;
          }

          try {
            if (!(response as any).ok()) {
              let bodySnippet = "";

              try {
                bodySnippet = await (response as any).text();
              } catch {
                bodySnippet = "";
              }

              const trimmedBody = bodySnippet.trim().slice(0, 1_000);
              const diagnostic =
                trimmedBody.length > 0 ? ` – ${trimmedBody}` : "";

              settle(
                "reject",
                new Error(
                  `Chat API request failed with ${(response as any).status()} ${(response as any).statusText()}${diagnostic}`
                )
              );
              return;
            }

            settle("resolve");
          } catch (error) {
            settle(
              "reject",
              error instanceof Error
                ? error
                : new Error("Chat API response handling failed")
            );
          }
        };

        const handleFailure = async (request: unknown) => {
          const candidate = request as any;

          if (!this.matchesChatApiRequest(candidate)) {
            return;
          }

          let diagnostic = "";
          try {
            // Normalise Playwright's optional `failure()` accessor so the
            // helper can surface the original network error text without
            // tripping strict type checks in the Vitest environment.
            const failureFn =
              candidate &&
              typeof candidate === "object" &&
              "failure" in candidate &&
              typeof (candidate as { failure?: unknown }).failure === "function"
                ? (candidate as { failure: () => unknown }).failure
                : null;

            const failureDetails = await Promise.resolve(
              failureFn ? failureFn() : null
            );
            // Some runtimes expose richer error payloads (Chromium) while
            // others only emit bare network codes. Gate access through a
            // structural check so we stay compatible everywhere.
            const failureText =
              failureDetails &&
              typeof failureDetails === "object" &&
              "errorText" in failureDetails &&
              typeof (failureDetails as { errorText?: unknown }).errorText ===
                "string"
                ? (failureDetails as { errorText: string }).errorText.trim()
                : "";
            diagnostic = failureText ? ` – ${failureText}` : "";
          } catch {
            diagnostic = "";
          }

          settle(
            "reject",
            new Error(
              `Chat API request failed before receiving a response${diagnostic}`
            )
          );
        };

        timer = setTimeout(() => {
          settle("reject", networkTimeoutMarker);
        }, networkTimeoutMs);

        page.on("response", handleResponse);
        page.on("requestfailed", handleFailure);
      });

      return;
    } catch (error) {
      if (error !== networkTimeoutMarker) {
        throw error instanceof Error
          ? error
          : new Error("Chat API request failed");
      }
    }

    const baselineSnapshot =
      this.pendingAssistantSnapshot ??
      (await this.captureAssistantSnapshot());

    await this.waitForUiStreamingFallback(baselineSnapshot, uiFallbackTimeoutMs);
  }

  private async waitForUiStreamingFallback(
    baseline: NonNullable<typeof this.pendingAssistantSnapshot>,
    timeoutMs: number
  ): Promise<void> {
    const toast = this.page.getByTestId("toast");

    const rawToastPromise = toast
      .waitFor({ state: "visible", timeout: timeoutMs })
      .then(async () => {
        const description = await toast
          .innerText()
          .then((value) => value.trim())
          .catch(() => "");

        const suffix = description.length > 0 ? `: ${description}` : "";
        throw new Error(`Chat UI reported an error toast${suffix}`);
      });
    const toastPromise = rawToastPromise.catch((error) => {
      throw error;
    });

    const rawStreamingPromise = this.page
      .waitForFunction(
        (args: {
          baselineCount: number;
          baselineLatestId: string | null;
          baselineLatestText: string;
          baselineArtifactCount: number;
        }) => {
          const assistantNodes = Array.from(
            document.querySelectorAll<HTMLElement>(
              '[data-testid="message-assistant"]'
            )
          );

          if (assistantNodes.length > args.baselineCount) {
            return true;
          }

          if (assistantNodes.length > 0) {
            const latestAssistant = assistantNodes[assistantNodes.length - 1];
            const latestId = latestAssistant.getAttribute("data-message-id");

            if (latestId && latestId !== args.baselineLatestId) {
              return true;
            }

            const latestText =
              latestAssistant
                .querySelector<HTMLElement>('[data-testid="message-content"]')
                ?.innerText.trim() ?? "";

            if (
              latestText.length > 0 &&
              latestText !== args.baselineLatestText
            ) {
              return true;
            }

            const latestArtifactCount =
              latestAssistant.querySelectorAll('[data-testid$="-artifact"]').length;

            if (latestArtifactCount > args.baselineArtifactCount) {
              return true;
            }
          }

          const loadingCount = document.querySelectorAll(
            '[data-testid="message-assistant-loading"]'
          ).length;

          return loadingCount > 0;
        },
        {
          baselineCount: baseline.count,
          baselineLatestId: baseline.latestMessageId,
          baselineLatestText: baseline.latestMessageText,
          baselineArtifactCount: baseline.latestArtifactCount,
        },
        { timeout: timeoutMs }
      )
      .then(() => {
        // The UI started streaming (spinner, text, or artefact delta).
      });
    const streamingPromise = rawStreamingPromise.catch((error) => {
      throw error;
    });

    try {
      await Promise.race([toastPromise, streamingPromise]);
    } catch (error) {
      if (isTimeoutLikeError(error)) {
        throw new Error("Timed out waiting for chat UI to start streaming");
      }
      throw error;
    } finally {
      rawToastPromise.catch(() => {});
      rawStreamingPromise.catch(() => {});
    }
  }

  private async waitForVoteRequest(direction: "up" | "down"): Promise<void> {
    const response = await this.page.waitForResponse((candidate) => {
      const request = candidate.request();
      if (!request || request.method() !== "PATCH") {
        return false;
      }

      const rawUrl = candidate.url();
      try {
        const { pathname } = new URL(rawUrl);
        if (pathname !== "/api/vote") {
          return false;
        }
      } catch {
        if (!rawUrl.includes("/api/vote")) {
          return false;
        }
      }

      try {
        const parse =
          typeof request.postDataJSON === "function"
            ? request.postDataJSON.bind(request)
            : null;
        const body = parse ? parse() : {};
        return body?.type === direction;
      } catch {
        return true;
      }
    }, { timeout: 15_000 });

    if (!response.ok()) {
      const status = response.status();
      const statusText = response.statusText();
      throw new Error(
        `Vote request failed with ${status} ${statusText}`
      );
    }
  }
  async expectToastToContain(text: string) {
    await expect(this.page.getByTestId("toast")).toContainText(text);
  }

  async openSideBar() {
    const sidebarToggleButton = this.page.getByTestId("sidebar-toggle-button");
    await sidebarToggleButton.click();
  }

  isScrolledToBottom(): Promise<boolean> {
    return this.scrollContainer.evaluate(
      (el) => Math.abs(el.scrollHeight - el.scrollTop - el.clientHeight) < 1
    );
  }

  async waitForScrollToBottom(timeout = 5000): Promise<void> {
    const start = Date.now();

    while (Date.now() - start < timeout) {
      if (await this.isScrolledToBottom()) {
        return;
      }
      await this.page.waitForTimeout(100);
    }

    throw new Error(`Timed out waiting for scroll bottom after ${timeout}ms`);
  }

  async sendMultipleMessages(
    count: number,
    makeMessage: (i: number) => string
  ) {
    for (let i = 0; i < count; i++) {
      await this.sendUserMessage(makeMessage(i));
      await this.isGenerationComplete();
    }
  }

  async scrollToTop(): Promise<void> {
    await this.scrollContainer.evaluate((element) => {
      element.scrollTo({ top: 0, behavior: "auto" });
      /**
       * Programmatic scrolls in Playwright do not always emit the `scroll`
       * event, which means React’s listeners would miss the state change and
       * keep the "scroll to bottom" button hidden. Dispatch the event manually
       * so the UI mirrors a real user interaction.
       */
      element.dispatchEvent(new Event("scroll"));
    });
  }
}

function isTimeoutLikeError(error: unknown): boolean {
  if (!error) {
    return false;
  }

  if (error instanceof playwrightErrors.TimeoutError) {
    return true;
  }

  if (error instanceof Error) {
    if (error.name === "TimeoutError") {
      return true;
    }

    return error.message.toLowerCase().includes("timeout");
  }

  return false;
}
