import fs from "node:fs";
import path from "node:path";
import {
  expect,
  type Page,
  type Locator,
  type Response as PlaywrightResponse,
  type Request as PlaywrightRequest,
  errors as playwrightErrors,
} from "@playwright/test";
import { z } from "zod";
import { chatModels, type ChatModel } from "@/lib/ai/models";
import { DEFAULT_ONBOARDING_SUGGESTION } from "@/lib/constants";

/**
 * Validate that the current page URL ends with a chat identifier without
 * coupling the assertion to a specific host or port. Playwright drives the app
 * on a dynamic base URL (port 3000 locally, 3100 during hermetic runs), so we
 * only assert on the `/chat/:id` suffix. The UUID shape mirrors the database
 * identifiers generated by Drizzle.
 */
const CHAT_ID_REGEX = /\/chat\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

/**
 * Streaming requests reuse the chat API namespace but append the chat
 * identifier before `/stream`. We match both the base route and streaming
 * suffix so the helper recognises edits and retries as well as brand new
 * chats, regardless of the query string Playwright attaches when retrying.
 */
const CHAT_STREAM_PATH_REGEX = /^\/api\/chat\/[\w-]+\/stream$/;

/**
 * Some Playwright runs rely on the automation toast bridge when the Sonner
 * portal hydrates slowly. Target both the native toast and the bridge element
 * so locator queries remain stable even when the fallback is active.
 */
const TOAST_LOCATOR = '[data-testid="toast"], #automation-toast-bridge';

/**
 * Hostnames that are considered internal to the application when Playwright is
 * driving the Next.js dev server. Restricting network assertions to this
 * safelist guarantees that helpers never wait on third-party requests (for
 * example calls to OpenAI) during hermetic test runs.
 */
const INTERNAL_HOSTNAME_WHITELIST = new Set([
  "localhost",
  "127.0.0.1",
  "0.0.0.0",
  "::1",
]);

/**
 * Snapshot of the assistant timeline captured right before triggering a new
 * generation. Defining the shape up front allows helper methods to reference
 * the type without relying on the `this` context — a pattern that keeps the
 * file compliant with `noImplicitThis` during the Next.js type-checking phase.
 */
type AssistantSnapshot = {
  count: number;
  latestMessageId: string | null;
  latestMessageText: string;
  latestArtifactCount: number;
};

/**
 * Zod schema capturing the standard API error envelope returned by the chat
 * routes. Parsing the body through this schema keeps the toast assertions type
 * safe without sprinkling manual `any` casts across the helper.
 */
const chatErrorEnvelopeSchema = z
  .object({
    error: z
      .object({
        code: z.string().optional(),
        message: z.string().optional(),
      })
      .optional(),
  })
  .passthrough();

type ChatErrorEnvelope = z.infer<typeof chatErrorEnvelopeSchema>;

export class ChatPage {
  /**
   * Surface the Playwright assertion helper so unit tests can substitute a
   * lightweight spy without mutating the imported module namespace.
   */
  static expect = expect;

  private readonly page: Page;

  /**
   * Snapshot of the assistant timeline captured right before triggering a new
   * generation. We compare the stored baseline with the live DOM while polling
   * so the helper recognises both brand-new bubbles and updates to the latest
   * message content or attached artefacts.
   */
  private pendingAssistantSnapshot: AssistantSnapshot | null = null;

  /**
   * Track the most recent vote request so the helper can await the matching
   * `/api/vote` response and avoid relying solely on transient UI signals.
   */
  private pendingVoteRequest: Promise<void> | null = null;

  /**
   * Record how many user messages were present before dispatching the current
   * action. Suggested quick actions append the bubble immediately while the UI
   * may still be hydrating its streaming indicators. Falling back to this
   * counter lets the polling guard unblock as soon as the DOM reflects the
   * optimistic user echo, even if the stop button or spinner never toggles.
   */
  private pendingUserMessageCount = 0;

  /**
   * Record whether the stop button was visible when the next generation cycle
   * started so polling can differentiate between the residual cooldown from the
   * previous run and a fresh streaming toggle.
   */
  private pendingStopButtonWasVisible = false;

  /**
   * Record the send button visibility before dispatching a message so the UI
   * polling fallback can recognise when the stop control takes over, even if
   * the spinner fails to render during fast hermetic runs.
   */
  private pendingSendButtonWasVisible = false;

  /**
   * Preserve the send button enabled state before dispatching a prompt. Certain
   * automation flows (for example suggested quick actions) keep the control
   * visible yet disable it instead of swapping in the stop button. Capturing the
   * baseline enabled flag allows the polling fallback to treat that transition
   * as proof that streaming started even when visibility stays unchanged.
   */
  private pendingSendButtonWasEnabled = false;

  /**
   * Mirror the automation bridge's chat signal counter so the network guard can
   * observe synthetic events emitted by the client bundle whenever a submission
   * is dispatched. The signals complement Playwright's network events and keep
   * the helpers resilient when fetch hooks miss the streaming transport.
   */
  private pendingChatSignalCount = 0;

  /**
   * Snapshot the composer value prior to dispatching a prompt. Suggested
   * actions pre-fill the textarea before immediately submitting, so the DOM
   * clearing that follows is a reliable indication that the UI kicked off the
   * new generation even when other streaming toggles are slow to appear.
   */
  private pendingComposerValue = "";

  /**
   * Flag whether the upcoming submission should clear a pre-seeded composer
   * value. When true, the network guard races a dedicated waiter against the
   * transport so suggestion-driven flows resolve as soon as the textarea is
   * emptied, even if Playwright misses the underlying fetch events.
   */
  private pendingComposerNeedsClear = false;

  /**
   * Remember the exact composer value that a suggestion is expected to stage
   * before submitting. The polling guard only treats the subsequent clearing as
   * progress once this value has been observed at least once, preventing early
   * exits that would otherwise occur while the DOM still reflects the empty
   * textarea baseline.
   */
  private pendingComposerPrefill: string | null = null;

  /**
   * Track the in-flight chat response watcher so flows that skip the immediate
   * await (for example stop-button assertions) can still surface transport
   * failures once the UI polling completes. Any rejection captured here is
   * rethrown the next time `isGenerationComplete` runs to keep diagnostics
   * deterministic across delayed awaits.
   */
  private pendingChatResponseWatcher: Promise<void> | null = null;

  /**
   * Buffer any error emitted by the deferred chat response watcher so the next
   * completion check can surface the failure even if the original submission
   * returned control early (for example when tests intentionally avoid waiting
   * for the full stream to exercise the stop button).
   */
  private pendingChatResponseError: Error | null = null;

  /**
   * Remember whether the suggested actions panel was visible before dispatching
   * the next submission. Suggested quick actions hide the grid immediately
   * after a selection, so tracking the baseline visibility gives the polling
   * guard another deterministic signal to recognise streaming progress without
   * depending solely on spinners or network hooks.
   */
  private pendingSuggestedActionsWereVisible = false;

  constructor(page: Page) {
    this.page = page;
  }

  get sendButton() {
    return this.page.getByTestId("send-button");
  }

  get stopButton() {
    return this.page.getByTestId("stop-button");
  }

  get multimodalInput() {
    return this.page.getByTestId("multimodal-input");
  }

  get scrollContainer() {
    return this.page.locator(".overflow-y-scroll");
  }

  get scrollToBottomButton() {
    return this.page.getByTestId("scroll-to-bottom-button");
  }

  async createNewChat() {
    await this.page.goto("/chat", {
      /**
       * Next.js app router streams the shell before every asset finishes
       * loading, which occasionally blocks the `load` event during cold Turbopack
       * starts. Waiting for `domcontentloaded` keeps the navigation resilient in
       * hermetic Playwright runs without masking legitimate network hangs.
       */
      waitUntil: "domcontentloaded",
    });

    await this.ensureChatSurfaceReady();
  }

  /**
   * Confirm that the chat surface rendered after navigation. The helper guards
   * against authentication regressions (a redirect to `/login`) and ensures the
   * input controls are visible before callers attempt to interact with them.
   */
  private async ensureChatSurfaceReady() {
    const currentUrl = new URL(this.page.url());

    if (currentUrl.pathname.startsWith("/login")) {
      throw new Error(
        "Expected an authenticated session before visiting /chat, but the app redirected to /login. " +
          "Ensure tests/setup/auth.setup.ts provisioned credentials via the regular sign-in flow."
      );
    }

    await this.page.waitForSelector('[data-testid="multimodal-input"]', {
      /**
       * Chat renders a sizeable component tree. Waiting for the primary input
       * avoids racing against hydration when Playwright runs in parallel.
       */
      state: "visible",
      timeout: 15_000,
    });

    await this.page.waitForSelector('[data-testid="send-button"]', {
      state: "visible",
      timeout: 15_000,
    });
  }

  getCurrentURL(): string {
    return this.page.url();
  }

  async sendUserMessage(
    message: string,
    options?: { waitForResponse?: boolean }
  ) {
    const waitForResponse = options?.waitForResponse ?? true;
    const { sendButtonEnabled } = await this.waitForComposerReady(message);

    await this.prepareForGeneration({ composerValueOverride: message });

    /**
     * Trigger the send action and the API wait concurrently so we capture the
     * network response associated with this submission. Surfacing transport
     * failures immediately makes the suite easier to debug than waiting for the
     * streaming assertions to eventually time out. When the editor exposes a
     * disabled submit control (an edge case observed during hydration races),
     * fall back to the native "Enter" workflow to mimic how end users submit
     * prompts through the textarea.
     */
    const submission = sendButtonEnabled
      ? this.sendButton.click()
      : this.page.evaluate(() => {
          const textarea = document.querySelector<
            HTMLTextAreaElement
          >("textarea[data-testid='multimodal-input']");

          if (!textarea) {
            throw new Error(
              "Unable to submit chat message because the composer textarea was not present in the DOM."
            );
          }

          const form = textarea.form;

          if (!form) {
            throw new Error(
              "Unable to submit chat message because the composer form element could not be resolved."
            );
          }

          form.requestSubmit();
        });

    const responseWatcher = this.waitForChatApiResponse();
    this.pendingChatResponseError = null;
    this.pendingChatResponseWatcher = responseWatcher;

    responseWatcher.catch((error) => {
      this.pendingChatResponseError =
        error instanceof Error
          ? error
          : new Error(
              error == null
                ? "Chat API request failed"
                : String(error)
            );
    });

    responseWatcher.finally(() => {
      if (this.pendingChatResponseWatcher === responseWatcher) {
        this.pendingChatResponseWatcher = null;
      }
    });

    if (waitForResponse) {
      await Promise.all([responseWatcher, submission]);
      this.pendingChatResponseWatcher = null;
      return;
    }

    await submission;

    await this.page.waitForSelector('[data-testid="stop-button"]', {
      state: "visible",
      timeout: 10_000,
    });
  }

  async isGenerationComplete() {
    const assistantMessages = this.page.getByTestId("message-assistant");

    if (this.pendingChatResponseError) {
      const error = this.pendingChatResponseError;
      this.pendingChatResponseError = null;
      this.pendingChatResponseWatcher = null;
      throw error;
    }

    if (this.pendingChatResponseWatcher) {
      try {
        await this.pendingChatResponseWatcher;
      } catch (error) {
        this.pendingChatResponseError =
          error instanceof Error
            ? error
            : new Error(
                error == null
                  ? "Chat API request failed"
                  : String(error)
              );
      } finally {
        this.pendingChatResponseWatcher = null;
      }

      if (this.pendingChatResponseError) {
        const error = this.pendingChatResponseError;
        this.pendingChatResponseError = null;
        throw error;
      }
    }

    const {
      count: initialAssistantCount,
      latestMessageId: initialLatestMessageId,
      latestMessageText: initialLatestMessage,
      latestArtifactCount: initialArtifactCount,
    } =
      this.pendingAssistantSnapshot ??
      (await this.captureAssistantSnapshot());

    this.pendingAssistantSnapshot = null;
    /**
     * Finance journeys often render artefacts (chart, backtest, news) without
     * adding textual content to the assistant bubble. Tracking the initial
     * artefact footprint lets us confirm the UI updated even when the message
     * copy stays empty – a scenario that previously caused the polling loop to
     * spin forever and eventually time out the Playwright run.
     */

    /**
     * Some chat journeys (notably the finance accessibility sweep) reuse the
     * same assistant bubble when multiple prompts run back to back. The DOM
     * still streams fresh content, but the overall assistant count remains
     * stable. Poll both the count and the text payload so we unblock as soon as
     * either a new bubble appears or the latest response finishes streaming.
     */
    await this.page.waitForFunction(
      (args: {
        initialAssistantCount: number;
        initialLatestMessageId: string | null;
        initialLatestMessage: string;
        initialArtifactCount: number;
      }) => {
        const {
          initialAssistantCount,
          initialLatestMessageId,
          initialLatestMessage,
          initialArtifactCount,
        } = args;

        const toast = document.querySelector<HTMLElement>('[data-testid="toast"]');
        const toastText = toast?.textContent?.trim() ?? '';
        if (toastText.length > 0) {
          throw new Error(
            `Chat surfaced an error toast while waiting for the assistant response: ${toastText}`
          );
        }

        const assistantNodes = Array.from(
          document.querySelectorAll<HTMLElement>('[data-testid="message-assistant"]')
        );
        const currentCount = assistantNodes.length;

        if (currentCount > initialAssistantCount) {
          return true;
        }

        if (currentCount === initialAssistantCount && currentCount > 0) {
          const latestAssistant = assistantNodes[currentCount - 1];
          const latestMessageId = latestAssistant.getAttribute('data-message-id');

          if (latestMessageId && latestMessageId !== initialLatestMessageId) {
            return true;
          }

          const latestContent =
            latestAssistant
              .querySelector<HTMLElement>('[data-testid="message-content"]')
              ?.innerText.trim() ?? '';

          if (latestContent.length > 0 && latestContent !== initialLatestMessage) {
            return true;
          }

          const latestArtifactCount = latestAssistant.querySelectorAll('[data-testid$="-artifact"]').length;

          if (latestArtifactCount > initialArtifactCount) {
            return true;
          }

          const loadingCount = document.querySelectorAll('[data-testid="message-assistant-loading"]').length;
          const stopButton = document.querySelector<HTMLElement>('[data-testid="stop-button"]');
          const stopVisible =
            !!stopButton &&
            stopButton.offsetParent !== null &&
            window.getComputedStyle(stopButton).visibility !== 'hidden';

          if (stopVisible) {
            /**
             * Inline edit submissions reuse the global composer state. When the
             * stop button is visible we know the chat helpers started
             * streaming, so the fallback can return immediately without
             * waiting for additional DOM signals.
             */
            return true;
          }
        }

        return false;
      },
      {
        initialAssistantCount,
        initialLatestMessageId,
        initialLatestMessage,
        initialArtifactCount,
      },
      { timeout: 60_000 }
    );

    /**
     * Inline edit submissions temporarily clear the trailing assistant reply
     * before the regeneration begins streaming. Ensure a fresh assistant
     * bubble is attached before continuing so downstream helpers never observe
     * an empty timeline (which previously triggered "No assistant message"
     * errors in the Playwright harness).
     */
    await expect(assistantMessages).not.toHaveCount(0, { timeout: 60_000 });

    /**
     * The assistant stream reuses the same container while piping tool results
     * into the UI. By the time we reach this section the guard above has either
     * observed a brand-new bubble or detected fresh content within the latest
     * one, so selecting `count() - 1` safely targets the resolved response even
     * when earlier interactions left history entries in the DOM.
     */

    const latestAssistantMessage = assistantMessages.nth(
      (await assistantMessages.count()) - 1
    );
    await latestAssistantMessage.waitFor({ state: "attached" });

    await expect(this.page.getByTestId("message-assistant-loading")).toHaveCount(0);
    await expect(this.page.getByTestId("stop-button")).toHaveCount(0);

    const sendButton = this.sendButton;
    await expect(sendButton).toBeVisible();

    const latestMessageContent = latestAssistantMessage.getByTestId(
      "message-content"
    );

    let previousText = "";
    let stableIterations = 0;

    for (let attempt = 0; attempt < 50; attempt++) {
      const currentText = (await latestMessageContent.innerText()).trim();

      if (currentText && currentText === previousText) {
        stableIterations += 1;
        if (stableIterations >= 2) {
          break;
        }
      } else {
        stableIterations = 0;
        previousText = currentText;
      }

      await this.page.waitForTimeout(200);
    }

    const [finalText, finalArtifactCount] = await Promise.all([
      latestMessageContent.innerText().then((value) => value.trim()),
      latestAssistantMessage
        .locator('[data-testid$="-artifact"]')
        .count()
        .catch(() => 0),
    ]);

    /**
     * Artefact-only responses intentionally leave the chat bubble empty while
     * rendering dedicated finance components. Accept either textual deltas or
     * newly attached artefacts so both interaction styles satisfy the
     * completion contract.
     */
    expect(finalText.length > 0 || finalArtifactCount > 0).toBe(true);
  }

  async isVoteComplete(direction: "up" | "down" = "up") {
    /**
     * Voting triggers a toast notification via `toast.promise`. Waiting on the
     * visual feedback keeps the helper independent from the underlying fetch
     * request so the e2e suite remains hermetic and does not rely on network
     * responses resolving.
     */
    const voteButton = this.page.getByTestId(
      direction === "up" ? "message-upvote" : "message-downvote"
    );

    const toast = this.page.locator(TOAST_LOCATOR).first();
    const successCopy =
      direction === "up" ? "Upvoted Response!" : "Downvoted Response!";

    /**
     * Sonner silently drops toast updates when another notification is already
     * visible. Rather than timing out the suite when the success toast never
     * renders, attempt to observe it with a short grace period and fall back to
     * the button state if the toast is skipped.
     */
    const toastAppeared = await toast
      .waitFor({ state: "visible", timeout: 2_000 })
      .then(() => true)
      .catch(() => false);

    if (toastAppeared) {
      await ChatPage.expect(toast).toContainText(successCopy);
    }

    if (this.pendingVoteRequest) {
      try {
        await this.pendingVoteRequest;
      } finally {
        this.pendingVoteRequest = null;
      }
    }

    /**
     * SWR mutates the cached vote state in the background. Give the UI a few
     * moments to reflect the disabled state locally before falling back to the
     * optimistic network confirmation above.
     */
    const disableDeadline = Date.now() + 10_000;
    while (Date.now() < disableDeadline) {
      if (await voteButton.isDisabled()) {
        return;
      }

      await this.page.waitForTimeout(200);
    }
  }

  async hasChatIdInUrl() {
    await expect(this.page).toHaveURL(CHAT_ID_REGEX);
  }

  async sendUserMessageFromSuggestion() {
    /**
     * Target the deterministic suggestion test identifier so the helper keeps
     * working even when the rendered label changes (for example due to
     * different font fallbacks in offline Playwright runs).
     */
    const suggestion = this.page.getByTestId("suggested-action-0");
    await ChatPage.expect(suggestion).toBeVisible({ timeout: 15_000 });

    const candidateTexts: string[] = [];
    // Gather every accessible label the button may expose so automation can
    // recover the intended prompt even when innerText is empty (for example,
    // during partially hydrated renders or when fonts fall back and collapse
    // whitespace differently).
    candidateTexts.push(await suggestion.innerText().catch(() => ""));

    const textContentCandidate = await suggestion.textContent().catch(() => null);
    if (textContentCandidate) {
      candidateTexts.push(textContentCandidate);
    }

    const ariaLabelCandidate = (await suggestion.getAttribute("aria-label")) ?? "";
    if (ariaLabelCandidate) {
      candidateTexts.push(ariaLabelCandidate);
    }

    const datasetCandidate = await suggestion
      .evaluate((node) => (node as HTMLElement).dataset?.suggestion ?? "")
      .catch(() => "");
    if (datasetCandidate) {
      candidateTexts.push(datasetCandidate);
    }

    // As a final guard, fall back to the baseline onboarding suggestion so the
    // helper can still drive the composer even if the DOM yields no readable
    // content (for example when an icon-only button is rendered).
    candidateTexts.push(DEFAULT_ONBOARDING_SUGGESTION);

    const normalisedSuggestion =
      candidateTexts
        .map((candidate) => candidate.trim())
        .find((candidate) => candidate.length > 0) ?? DEFAULT_ONBOARDING_SUGGESTION;

    const composerOverride = normalisedSuggestion;

    const userMessages = this.page.getByTestId("message-user");
    const initialUserCount = await userMessages.count();
    const targetUserCount = initialUserCount + 1;

    await this.prepareForGeneration({
      composerValueOverride: composerOverride,
    });

    const networkWatcher = this.waitForChatApiResponse();
    networkWatcher.catch(() => {});

    await suggestion.click();

    const awaitUserBubble = async (timeout: number) => {
      await ChatPage.expect(userMessages).toHaveCount(targetUserCount, {
        timeout,
      });
    };

    try {
      await awaitUserBubble(7_500);
      await networkWatcher.catch(() => {});
      return;
    } catch (initialError) {
      const composerValue = await this.multimodalInput
        .inputValue()
        .catch(() => "");
      const signalCount = await this.page
        .evaluate(() => {
          const globalWindow = window as typeof window & {
            __PLAYWRIGHT_CHAT_SIGNALS__?: Array<unknown>;
          };

          return Array.isArray(globalWindow.__PLAYWRIGHT_CHAT_SIGNALS__)
            ? globalWindow.__PLAYWRIGHT_CHAT_SIGNALS__!.length
            : 0;
        })
        .catch(() => 0);
      const stopVisible = await this.stopButton.isVisible().catch(() => false);
      const diagnostic =
        composerValue.trim().length > 0
          ? ` Composer retained value: "${composerValue}".`
          : " Composer remained empty.";

      const baseError =
        initialError instanceof Error
          ? initialError
          : new Error(String(initialError));

      const fallbackPrompt =
        composerOverride && composerOverride.trim().length > 0
          ? composerOverride
          : normalisedSuggestion;

      if (!fallbackPrompt || fallbackPrompt.trim().length === 0) {
        throw new Error(
          "Suggested action did not stage any text to send." +
            diagnostic +
            ` Signals observed: ${signalCount}. Stop button visible: ${stopVisible}.`,
          { cause: baseError }
        );
      }

      const { sendButtonEnabled } = await this.waitForComposerReady(
        fallbackPrompt
      );

      await this.prepareForGeneration({
        composerValueOverride: fallbackPrompt,
      });

      const manualWatcher = this.waitForChatApiResponse();
      manualWatcher.catch(() => {});

      if (sendButtonEnabled) {
        await this.sendButton.click();
      } else {
        await this.multimodalInput.press("Enter");
      }

      try {
        await awaitUserBubble(10_000);
      } catch (fallbackError) {
        const latestComposerValue = await this.multimodalInput
          .inputValue()
          .catch(() => "");
        const fallbackDiagnostic =
          latestComposerValue.trim().length > 0
            ? ` Composer retained value: "${latestComposerValue}".`
            : " Composer remained empty.";

        throw new Error(
          "Failed to send the suggested prompt via automation fallback." +
            fallbackDiagnostic,
          fallbackError instanceof Error
            ? { cause: fallbackError }
            : undefined
        );
      }

      await manualWatcher.catch(() => {});

      return;
    }
  }

  async isElementVisible(elementId: string) {
    await expect(this.page.getByTestId(elementId)).toBeVisible();
  }

  async isElementNotVisible(elementId: string) {
    await expect(this.page.getByTestId(elementId)).not.toBeVisible();
  }

  async addImageAttachment() {
    const attachmentsButton = this.page.getByTestId("attachments-button");

    /**
     * Reasoning models disable file uploads in the composer. When the current
     * chat session uses that model, temporarily switch back to the default
     * conversational model so the attachment preview renders just like it does
     * in production. This mirrors the behaviour a user would follow manually
     * and keeps the Playwright journey deterministic.
     */
    if (await attachmentsButton.isDisabled()) {
      const fallbackModel =
        chatModels.find((model) => model.id === "chat-model") ?? chatModels[0];

      if (!fallbackModel) {
        throw new Error("Unable to determine the default chat model");
      }

      await this.chooseModelFromSelector(fallbackModel.id);
      await expect(attachmentsButton).toBeEnabled();
    }

    this.page.on("filechooser", async (fileChooser) => {
      const filePath = path.join(
        process.cwd(),
        "public",
        "images",
        "mouth of the seine, monet.jpg"
      );
      const imageBuffer = fs.readFileSync(filePath);

      await fileChooser.setFiles({
        name: "mouth of the seine, monet.jpg",
        mimeType: "image/jpeg",
        buffer: imageBuffer,
      });
    });

    await attachmentsButton.click();
  }

  async getSelectedModel() {
    const modelId = await this.page.getByTestId("model-selector").innerText();
    return modelId;
  }

  async chooseModelFromSelector(chatModelId: string) {
    const chatModel = chatModels.find(
      (currentChatModel) => currentChatModel.id === chatModelId
    );

    if (!chatModel) {
      throw new Error(`Model with id ${chatModelId} not found`);
    }

    const selectorTrigger = this.page.getByTestId("model-selector");

    // Wait for the selector trigger to hydrate before attempting to interact.
    await expect(selectorTrigger).toBeVisible({ timeout: 60_000 });
    await expect(selectorTrigger).toBeEnabled();

    await selectorTrigger.click();

    const selectorItem = await this.resolveModelSelectorItem({
      chatModel,
      timeoutMs: 60_000,
    });

    await expect(selectorItem).toBeVisible({ timeout: 60_000 });
    await selectorItem.click();

    expect(await this.getSelectedModel()).toBe(chatModel.name);
  }

  async getSelectedVisibility() {
    const visibilityId = await this.page
      .getByTestId("visibility-selector")
      .innerText();
    return visibilityId;
  }

  async chooseVisibilityFromSelector(chatVisibility: "public" | "private") {
    await this.page.getByTestId("visibility-selector").click();
    await this.page
      .getByTestId(`visibility-selector-item-${chatVisibility}`)
      .click();
    expect(await this.getSelectedVisibility()).toBe(chatVisibility);
  }

  async getRecentAssistantMessage() {
    const assistantLocator = this.page.getByTestId("message-assistant");

    /**
     * Inline edit regenerations temporarily clear the assistant bubble before
     * the new response attaches.  Wait for the element collection to repopulate
     * so downstream assertions never observe an empty timeline.
     */
    await expect(assistantLocator).not.toHaveCount(0, { timeout: 60_000 });

    const messageElements = await assistantLocator.all();
    const lastMessageElement = messageElements.at(-1);

    if (!lastMessageElement) {
      throw new Error("No assistant message found");
    }

    const content = await lastMessageElement
      .getByTestId("message-content")
      .innerText()
      .then((value) => value?.trim() ?? "")
      .catch(() => "");

    const reasoningContainer = lastMessageElement.getByTestId(
      "message-reasoning"
    );
    const reasoningTrigger = lastMessageElement.getByTestId(
      "message-reasoning-trigger"
    );
    const reasoningContent = lastMessageElement.getByTestId(
      "message-reasoning-content"
    );

    const reasoningText = await reasoningContent
      .waitFor({ state: "attached", timeout: 5_000 })
      .then(async () => {
        const isVisible = await reasoningContent
          .isVisible()
          .catch(() => false);

        if (!isVisible) {
          // Auto-close animations hide the reasoning snippet almost
          // immediately after streaming finishes. Re-open the accordion so we
          // can capture the full explanation before returning it to callers.
          await reasoningTrigger.click();
          await reasoningContent.waitFor({ state: "visible", timeout: 5_000 });
        }

        return reasoningContent
          .innerText()
          .then((value) => value?.trim() ?? "")
          .catch(() => null);
      })
      .catch(() => null);

    const self = this;

    return {
      element: lastMessageElement,
      content,
      reasoning: reasoningText,
      reasoningElement: reasoningContainer,
      async toggleReasoningVisibility() {
        const currentState = await reasoningContent
          .getAttribute("data-state")
          .catch(() => null);

        await reasoningTrigger.click();

        // Defensive guard: if the attribute is missing we bail out rather
        // than waiting forever on an assertion that would never settle.
        if (!currentState) {
          return;
        }

        const nextState = currentState === "open" ? "closed" : "open";

        await expect(reasoningContent).toHaveAttribute(
          "data-state",
          nextState
        );
      },
      async upvote() {
        const voteAwaiter = self.waitForVoteRequest("up");
        self.pendingVoteRequest = voteAwaiter;
        await Promise.all([
          voteAwaiter.catch(() => {
            /* handled in isVoteComplete */
          }),
          lastMessageElement.getByTestId("message-upvote").click(),
        ]);
      },
      async downvote() {
        const voteAwaiter = self.waitForVoteRequest("down");
        self.pendingVoteRequest = voteAwaiter;
        await Promise.all([
          voteAwaiter.catch(() => {
            /* handled in isVoteComplete */
          }),
          lastMessageElement.getByTestId("message-downvote").click(),
        ]);
      },
    };
  }

  async getRecentUserMessage() {
    const messageElements = await this.page.getByTestId("message-user").all();
    const lastMessageElement = messageElements.at(-1);

    if (!lastMessageElement) {
      throw new Error("No user message found");
    }

    const content = await lastMessageElement
      .getByTestId("message-content")
      .innerText()
      .then((value) => value?.trim() ?? "")
      .catch(() => "");

    const hasAttachments = await lastMessageElement
      .getByTestId("message-attachments")
      .isVisible()
      .catch(() => false);

    const attachments = hasAttachments
      ? await lastMessageElement.getByTestId("message-attachments").all()
      : [];

    const page = this.page;
    const waitForChatApiResponse = this.waitForChatApiResponse.bind(this);
    const self = this;

    return {
      element: lastMessageElement,
      content,
      attachments,
      async edit(newMessage: string) {
        await page.getByTestId("message-edit-button").click();
        await page.getByTestId("message-editor").fill(newMessage);
        /**
         * Editing often happens after the tester scrolls through history. Make
         * sure the viewport is anchored to the latest messages so the inline
         * editor’s send button is visible and Playwright doesn’t have to fight
         * with the floating “scroll to bottom” control.
         */
        await self.waitForScrollToBottom().catch(() => {});
        await self.prepareForGeneration();
        await Promise.all([
          waitForChatApiResponse(),
          page.getByTestId("message-editor-send-button").click(),
        ]);
        await page
          .getByTestId("message-editor-send-button")
          .waitFor({ state: "hidden" })
          .catch(async () => {
            /**
             * Some transports remove the editor from the DOM entirely instead of
             * hiding the send button. Falling back to `detached` keeps the
             * helper resilient across UI refactors while still guaranteeing the
             * edit cycle finished.
             */
            await page
              .getByTestId("message-editor-send-button")
              .waitFor({ state: "detached" });
          });
      },
    };
  }

  /**
   * Capture the current assistant state before dispatching a new user action so
   * `isGenerationComplete` can later diff the DOM against a stable baseline.
   * This keeps the polling logic deterministic across synchronous mocks and
   * long-running finance tool chains.
   */
  private async prepareForGeneration({
    composerValueOverride,
  }: {
    composerValueOverride?: string;
  } = {}): Promise<void> {
    this.pendingAssistantSnapshot = await this.captureAssistantSnapshot();
    this.pendingUserMessageCount = await this.page
      .getByTestId("message-user")
      .count()
      .catch(() => 0);
    this.pendingStopButtonWasVisible = await this.stopButton
      .isVisible()
      .catch(() => false);
    this.pendingSendButtonWasVisible = await this.sendButton
      .isVisible()
      .catch(() => false);
    this.pendingSendButtonWasEnabled = await this.sendButton
      .isEnabled()
      .catch(() => false);
    if (typeof composerValueOverride === "string") {
      this.pendingComposerValue = composerValueOverride;
      this.pendingComposerNeedsClear =
        composerValueOverride.trim().length > 0;
      this.pendingComposerPrefill = composerValueOverride;
    } else {
      const composerValue = await this.multimodalInput
        .inputValue()
        .catch(() => "");

      this.pendingComposerValue = composerValue;
      this.pendingComposerNeedsClear = composerValue.trim().length > 0;
      this.pendingComposerPrefill = null;
    }
    this.pendingChatSignalCount = await this.page
      .evaluate(() => {
        const globalWindow = window as typeof window & {
          __PLAYWRIGHT_CHAT_SIGNALS__?: Array<unknown>;
        };

        return Array.isArray(globalWindow.__PLAYWRIGHT_CHAT_SIGNALS__)
          ? globalWindow.__PLAYWRIGHT_CHAT_SIGNALS__.length
          : 0;
      })
      .catch(() => 0);

    this.pendingSuggestedActionsWereVisible = await this.page
      .getByTestId("suggested-actions")
      .isVisible()
      .catch(() => false);
  }

  /**
   * Seeds the controlled composer with the outbound prompt and waits for the
   * UI to acknowledge that input.  The helper continually replays the text
   * whenever hydration swaps out the textarea element and returns whether the
   * send button ended up enabled.  Callers can fall back to submitting via the
   * Enter key whenever the button stays disabled.
   */
  private async waitForComposerReady(
    message: string,
    options?: { timeout?: number; pollInterval?: number }
  ): Promise<{ sendButtonEnabled: boolean }> {
    const timeout = options?.timeout ?? 30_000;
    const pollInterval = options?.pollInterval ?? 100;
    const deadline = Date.now() + timeout;

    const composer = this.multimodalInput;
    const sendButton = this.sendButton;
    const stopButton = this.stopButton;

    // Give the controlled textarea focus and seed the outbound prompt exactly
    // as a user would: clear any residue and type the message character by
    // character so React receives the full cascade of keyboard events.
    await composer.click();
    await composer.fill("");
    await composer.type(message);
    await this.synchroniseComposerValue(message).catch(() => {});

    let lastComposerValue = "";
    let lastSendEnabled = false;
    let stopVisible = false;
    let rescueAttempts = 0;

    while (Date.now() < deadline) {
      [lastComposerValue, lastSendEnabled, stopVisible] = await Promise.all([
        composer.inputValue().catch(() => ""),
        sendButton.isEnabled().catch(() => false),
        stopButton.isVisible().catch(() => false),
      ]);

      if (lastComposerValue === message && lastSendEnabled && !stopVisible) {
        return { sendButtonEnabled: true };
      }

      // Hydration occasionally replaces the textarea node, wiping the value in
      // the process. When that happens, re-seed the input so the composer state
      // matches the outbound message and Playwright does not submit an empty
      // payload.
      if (lastComposerValue !== message) {
        await composer.fill("");
        await composer.type(message);
        await this.synchroniseComposerValue(message).catch(() => {});
      } else if (!lastSendEnabled && !stopVisible) {
        // If the DOM already mirrors the outbound prompt but the submit button
        // remains disabled, force a synthetic input event so React flushes the
        // controlled state. Without this guard the Playwright driver can outpace
        // state reconciliation, leaving the composer visually populated while
        // the send button stays inert.
        rescueAttempts += 1;
        if (rescueAttempts <= 3) {
          await this.synchroniseComposerValue(message).catch(() => {});
        }
      }

      const remaining = Math.max(0, deadline - Date.now());
      await this.page.waitForTimeout(Math.min(pollInterval, remaining));
    }

    const normalizedComposerValue = lastComposerValue.trim();
    const normalizedMessage = message.trim();

    if (normalizedComposerValue === normalizedMessage && !stopVisible) {
      return { sendButtonEnabled: lastSendEnabled };
    }

    const composerDiagnostic =
      normalizedComposerValue.length > 0
        ? ` Composer retained value: "${lastComposerValue}".`
        : " Composer remained empty.";
    const sendDiagnostic = lastSendEnabled ? "" : " Send button stayed disabled.";
    const stopDiagnostic = stopVisible
      ? " Stop button remained visible, indicating an active stream."
      : "";

    throw new Error(
      "Composer never became ready before submission." +
        composerDiagnostic +
        sendDiagnostic +
        stopDiagnostic
    );
  }

  private async synchroniseComposerValue(value: string): Promise<void> {
    await this.multimodalInput
      .evaluate((textarea, nextValue) => {
        if (!(textarea instanceof HTMLTextAreaElement)) {
          return;
        }

        const descriptor = Object.getOwnPropertyDescriptor(
          HTMLTextAreaElement.prototype,
          "value"
        );

        descriptor?.set?.call(textarea, nextValue);
        textarea.dispatchEvent(new Event("input", { bubbles: true }));
        textarea.dispatchEvent(new Event("change", { bubbles: true }));
      }, value)
      .catch(async () => {
        await this.multimodalInput.fill(value);
      });
  }

  private async captureAssistantSnapshot(): Promise<AssistantSnapshot> {
    const assistantMessages = this.page.getByTestId("message-assistant");
    const count = await assistantMessages.count();

    if (count === 0) {
      return {
        count,
        latestArtifactCount: 0,
        latestMessageId: null,
        latestMessageText: "",
      };
    }

    const latestAssistant = assistantMessages.nth(count - 1);
    const latestMessageId = await latestAssistant
      .getAttribute("data-message-id")
      .catch(() => null);
    const latestMessageText = await latestAssistant
      .getByTestId("message-content")
      .innerText()
      .then((value) => value.trim())
      .catch(() => "");
    const latestArtifactCount = await latestAssistant
      .locator('[data-testid$="-artifact"]')
      .count()
      .catch(() => 0);

    return {
      count,
      latestArtifactCount,
      latestMessageId,
      latestMessageText,
    };
  }

  /**
   * Determine whether a Playwright network primitive represents a chat API
   * request. The helper intentionally accepts both `Request` objects (emitted
   * by the `requestfailed` event) and `Response.request()` handles so the
   * matching logic stays centralised and less error-prone.
   */
  private matchesChatApiRequest(candidate: unknown): boolean {
    if (!candidate || typeof candidate !== "object") {
      return false;
    }

    const maybeRequest = candidate as {
      url?: unknown;
      method?: unknown;
    };

    if (typeof maybeRequest.url !== "function") {
      return false;
    }

    const method =
      typeof maybeRequest.method === "function"
        ? maybeRequest.method()
        : null;
    const normalizedMethod = method?.toUpperCase() ?? null;

    const rawUrl = maybeRequest.url();

    try {
      const parsedUrl = new URL(rawUrl);

      if (!this.isInternalApiUrl(parsedUrl)) {
        return false;
      }

      const { pathname } = parsedUrl;

      const isStreamPath = CHAT_STREAM_PATH_REGEX.test(pathname);
      // Accept nested chat endpoints (for example, edit or follow-up routes)
      // that live under the /api/chat namespace so network hooks observe the
      // transports powering inline message edits in addition to the root chat
      // entry point.
      const isChatNamespace =
        pathname === "/api/chat" || pathname.startsWith("/api/chat/");

      if (!isChatNamespace && !isStreamPath) {
        return false;
      }

      if (!normalizedMethod) {
        return true;
      }

      if (["POST", "PATCH", "PUT"].includes(normalizedMethod)) {
        return true;
      }

      if (normalizedMethod === "GET") {
        /**
         * The Vercel AI SDK resumes Server-Sent Event streams via
         * `GET /api/chat/:id/stream`. Accept the read transport so suggestion
         * helpers observe the streaming hook without waiting for UI fallbacks.
         */
        return isStreamPath;
      }

      return false;
    } catch {
      /**
       * Unit tests occasionally stub the Playwright request object with bare
       * relative URLs. Falling back to a substring check keeps the predicate
       * permissive for those scenarios while the production code continues to
       * rely on full URL parsing.
       */
      const includesChatPath = rawUrl.includes("/api/chat");
      const includesStreamSegment = rawUrl.includes("/stream");

      if (!includesChatPath) {
        return false;
      }

      if (!normalizedMethod) {
        return true;
      }

      if (["POST", "PATCH", "PUT"].includes(normalizedMethod)) {
        return true;
      }

      if (normalizedMethod === "GET") {
        return includesStreamSegment;
      }

      return false;
    }
  }

  /**
   * Determine whether the provided absolute URL points to the locally hosted
   * Next.js application. Playwright tests run against a dev server bound to a
   * loopback interface, so any other hostname would represent an external API
   * call that should be ignored in hermetic assertions.
   */
  private isInternalApiUrl(url: URL): boolean {
    if (INTERNAL_HOSTNAME_WHITELIST.has(url.hostname.toLowerCase())) {
      return true;
    }

    const currentPageOrigin = this.safeResolveCurrentOrigin();
    if (currentPageOrigin && currentPageOrigin.origin === url.origin) {
      return true;
    }

    return false;
  }

  /**
   * Capture the origin of the current page URL, swallowing any parsing errors
   * (for example `about:blank` during the initial navigation) so callers can
   * gracefully fall back to the hostname whitelist.
   */
  private safeResolveCurrentOrigin(): URL | null {
    try {
      return new URL(this.page.url());
    } catch {
      return null;
    }
  }

  private async waitForChatApiResponse(): Promise<void> {
    /**
     * Prefer detecting the transport via Playwright's network events so we
     * surface HTTP failures immediately. If the browser driver does not emit
     * the expected hooks (Playwright regressions, streaming nuances, etc.), we
     * fall back to observing the chat UI so the helper still unblocks once the
     * stop button appears.
     */
    const networkTimeoutMarker = Symbol("chat-network-timeout");
    const networkTimeoutMs = 15_000;
    const uiFallbackTimeoutMs = 45_000;

    const baselineSnapshot =
      this.pendingAssistantSnapshot ??
      (await this.captureAssistantSnapshot());

    /**
     * Kick off the UI polling guard alongside the network listener so we reuse
     * the baseline state no matter which signal resolves first. When the
     * Playwright driver misses the streaming transport entirely, the DOM still
     * reflects progress almost immediately (new user echoes, send-button
     * toggles, etc.), so starting the fallback eagerly avoids idling for the
     * full network timeout before observing the UI transition we already
     * expect.
     */
    const baselineSignalCount = this.pendingChatSignalCount ?? 0;

    const baselineComposerValue = this.pendingComposerValue ?? "";
    const shouldWatchComposerClear =
      this.pendingComposerNeedsClear &&
      baselineComposerValue.trim().length > 0;

    const fallbackPromise = this.waitForUiStreamingFallback({
      baseline: baselineSnapshot,
      baselineUserMessageCount: this.pendingUserMessageCount,
      baselineStopButtonVisible: this.pendingStopButtonWasVisible,
      baselineSendButtonVisible: this.pendingSendButtonWasVisible,
      baselineSendButtonEnabled: this.pendingSendButtonWasEnabled,
      baselineChatSignalCount: baselineSignalCount,
      baselineComposerValue,
      baselineSuggestedActionsVisible: this.pendingSuggestedActionsWereVisible,
      timeoutMs: uiFallbackTimeoutMs,
    });

    const page = this.page;
    const browserContext =
      typeof page.context === "function" ? page.context() : null;

    type NetworkEvent =
      | { kind: "request"; request: PlaywrightRequest }
      | { kind: "response"; response: PlaywrightResponse }
      | { kind: "failure"; request: PlaywrightRequest }
      | { kind: "signal" };

    const requestMatcher = (candidate: unknown) =>
      this.matchesChatApiRequest(candidate);

    const watchers: Array<Promise<NetworkEvent>> = [];

    const pushWatcher = (promise: Promise<NetworkEvent>) => {
      watchers.push(
        promise.catch((error) => {
          if (isTimeoutLikeError(error)) {
            return new Promise<NetworkEvent>(() => {});
          }
          throw error;
        })
      );
    };

    pushWatcher(
      page
        .waitForFunction(
          (baseline) => {
            const globalWindow = window as typeof window & {
              __PLAYWRIGHT_CHAT_SIGNALS__?: Array<unknown>;
            };
            const signals = globalWindow.__PLAYWRIGHT_CHAT_SIGNALS__;
            return Array.isArray(signals) && signals.length > baseline;
          },
          baselineSignalCount,
          { timeout: networkTimeoutMs }
        )
        .then(() => ({ kind: "signal" }))
    );

    if (shouldWatchComposerClear) {
      pushWatcher(
        page
          .waitForFunction(
            (baseline: string) => {
              const textarea = document.querySelector<
                HTMLTextAreaElement
              >('textarea[data-testid="multimodal-input"]');

              if (!textarea) {
                return false;
              }

              const value = textarea.value;
              return value.trim().length === 0 && value !== baseline;
            },
            baselineComposerValue,
            { timeout: networkTimeoutMs }
          )
          .then(() => ({ kind: "signal" }))
      );
    }

    pushWatcher(
      page
        .waitForRequest((request) => requestMatcher(request))
        .then((request) => ({ kind: "request", request }))
    );

    pushWatcher(
      page
        .waitForResponse((response) => requestMatcher(response.request()))
        .then((response) => ({ kind: "response", response }))
    );

    pushWatcher(
      page
        .waitForEvent("requestfailed", {
          predicate: (request) => requestMatcher(request),
        })
        .then((request) => ({ kind: "failure", request }))
    );

    if (browserContext && typeof browserContext.waitForEvent === "function") {
      pushWatcher(
        browserContext
          .waitForEvent("request", {
            predicate: (request) => requestMatcher(request),
          })
          .then((request) => ({ kind: "request", request }))
      );

      pushWatcher(
        browserContext
          .waitForEvent("response", {
            predicate: (response) =>
              requestMatcher(response.request()),
          })
          .then((response) => ({ kind: "response", response }))
      );

      pushWatcher(
        browserContext
          .waitForEvent("requestfailed", {
            predicate: (request) => requestMatcher(request),
          })
          .then((request) => ({ kind: "failure", request }))
      );
    }

    let timer: ReturnType<typeof setTimeout> | null = null;
    let shouldAwaitFallback = false;

    try {
      const networkResult = await Promise.race<NetworkEvent | never>([
        ...watchers,
        new Promise<never>((_, reject) => {
          timer = setTimeout(
            () => reject(networkTimeoutMarker),
            networkTimeoutMs
          );
        }),
      ]);

      fallbackPromise.catch(() => {});

      if (networkResult.kind === "response") {
        const response = networkResult.response;
        try {
          if (!response.ok()) {
            const formattedError = await this.inspectRejectedChatResponse(
              response
            );
            throw new Error(formattedError);
          }
        } catch (error) {
          throw error instanceof Error
            ? error
            : new Error("Chat API response handling failed");
        }

        this.pendingComposerNeedsClear = false;
        return;
      }

      if (networkResult.kind === "failure") {
        const candidate = networkResult.request;
        let diagnostic = "";
        let normalizedDiagnostic = "";
        try {
          const failureDetails = await Promise.resolve(candidate.failure());
          const failureText = failureDetails?.errorText?.trim() ?? "";
          diagnostic = failureText ? ` – ${failureText}` : "";
          normalizedDiagnostic = failureText.toUpperCase();
        } catch {
          diagnostic = "";
          normalizedDiagnostic = "";
        }

        const offlineFailureSignals = [
          "ENETUNREACH",
          "ERR_NETWORK_CHANGED",
          "ERR_INTERNET_DISCONNECTED",
          "ERR_NETWORK_IO_SUSPENDED",
          "ERR_CONNECTION_REFUSED",
          "ERR_CONNECTION_RESET",
          "ERR_ADDRESS_UNREACHABLE",
        ];

        if (
          offlineFailureSignals.some((signal) =>
            normalizedDiagnostic.includes(signal)
          )
        ) {
          console.warn(
            "Chat API network request failed in offline mode; falling back to UI polling.",
            {
              failure:
                diagnostic.length > 0
                  ? diagnostic.trim().replace(/^–\s*/, "")
                  : offlineFailureSignals.find((signal) =>
                      normalizedDiagnostic.includes(signal)
                    ),
              url:
                typeof candidate?.url === "function"
                  ? candidate.url()
                  : undefined,
            }
          );

          throw networkTimeoutMarker;
        }

        this.pendingComposerNeedsClear = false;

        throw new Error(
          `Chat API request failed before receiving a response${diagnostic}`
        );
      }

      if (networkResult.kind === "signal") {
        this.pendingComposerNeedsClear = false;
        return;
      }

      if (networkResult.kind === "request") {
        const request = networkResult.request;

        /**
         * Playwright's `request.response()` resolves with `null` when the
         * transport fails before a response is available. Mirror the
         * production polling guard by racing the response promise against a
         * short timeout so hermetic tests unblock even when the browser never
         * surfaces a terminal payload.
         */
        const responsePromise =
          typeof request.response === "function"
            ? request.response()
            : Promise.resolve<PlaywrightResponse | null>(null);

        try {
          const response = await Promise.race<PlaywrightResponse | null>([
            Promise.resolve(responsePromise),
            new Promise<PlaywrightResponse | null>((resolve) =>
              setTimeout(() => resolve(null), 1_000)
            ),
          ]);

          if (response && !response.ok()) {
            const formattedError = await this.inspectRejectedChatResponse(
              response
            );
            throw new Error(formattedError);
          }
        } catch (error) {
          if (error === networkTimeoutMarker) {
            throw error;
          }

          throw error instanceof Error
            ? error
            : new Error("Chat API request inspection failed");
        }

        this.pendingComposerNeedsClear = false;
        return;
      }

      return;
    } catch (error) {
      if (error !== networkTimeoutMarker) {
        fallbackPromise.catch(() => {});
        this.pendingComposerNeedsClear = false;
        throw error instanceof Error
          ? error
          : new Error("Chat API request failed");
      }

      shouldAwaitFallback = true;
    } finally {
      if (timer) {
        clearTimeout(timer);
      }
      for (const watcher of watchers) {
        watcher.catch(() => {});
      }
    }

    if (!shouldAwaitFallback) {
      return;
    }

    try {
      await fallbackPromise;
    } finally {
      fallbackPromise.catch(() => {});
      this.pendingComposerNeedsClear = false;
    }
  }

  private async waitForUiStreamingFallback({
    baseline,
    baselineUserMessageCount,
    baselineStopButtonVisible,
    baselineSendButtonVisible,
    baselineSendButtonEnabled,
    baselineChatSignalCount,
    baselineComposerValue,
    baselineSuggestedActionsVisible,
    timeoutMs,
  }: {
    baseline: AssistantSnapshot;
    baselineUserMessageCount: number;
    baselineStopButtonVisible: boolean;
    baselineSendButtonVisible: boolean;
    baselineSendButtonEnabled: boolean;
    baselineChatSignalCount: number;
    baselineComposerValue: string;
    baselineSuggestedActionsVisible: boolean;
    timeoutMs: number;
  }): Promise<void> {
    const toast = this.page.locator(TOAST_LOCATOR).first();

    const rawToastPromise = toast
      .waitFor({ state: "visible", timeout: timeoutMs })
      .then(async () => {
        const description = await toast
          .innerText()
          .then((value) => value.trim())
          .catch(() => "");

        const suffix = description.length > 0 ? `: ${description}` : "";
        throw new Error(`Chat UI reported an error toast${suffix}`);
      });
    const toastPromise = rawToastPromise.catch((error) => {
      throw error;
    });

    const streamingPromise = this.pollForStreamingChange({
      baseline,
      baselineUserMessageCount,
      baselineStopButtonVisible,
      baselineSendButtonVisible,
      baselineSendButtonEnabled,
      baselineChatSignalCount,
      baselineComposerValue,
      baselineSuggestedActionsVisible,
      timeoutMs,
    });

    try {
      await Promise.race([toastPromise, streamingPromise]);
    } catch (error) {
      if (isTimeoutLikeError(error)) {
        throw new Error("Timed out waiting for chat UI to start streaming");
      }
      throw error;
    } finally {
      rawToastPromise.catch(() => {});
      streamingPromise.catch(() => {});
    }
  }

  private async resolveModelSelectorItem({
    chatModel,
    timeoutMs,
  }: {
    chatModel: ChatModel;
    timeoutMs: number;
  }): Promise<Locator> {
    const deadline = Date.now() + timeoutMs;
    const testIdLocator = this.page.getByTestId(
      `model-selector-item-${chatModel.id}`
    );
    const optionLocator = this.page
      .getByRole("option", { name: chatModel.name })
      .first();
    const menuItemLocator = this.page
      .getByRole("menuitem", { name: chatModel.name })
      .first();

    while (Date.now() < deadline) {
      if ((await testIdLocator.count().catch(() => 0)) > 0) {
        return testIdLocator.first();
      }

      if ((await optionLocator.count().catch(() => 0)) > 0) {
        return optionLocator;
      }

      if ((await menuItemLocator.count().catch(() => 0)) > 0) {
        return menuItemLocator;
      }

      await this.page.waitForTimeout(100);
    }

    throw new Error(
      `Unable to locate the model selector option for "${chatModel.name}".`
    );
  }

  private async pollForStreamingChange({
    baseline,
    baselineUserMessageCount,
    baselineStopButtonVisible,
    baselineSendButtonVisible,
    baselineSendButtonEnabled,
    baselineChatSignalCount,
    baselineComposerValue,
    baselineSuggestedActionsVisible,
    timeoutMs,
  }: {
    baseline: AssistantSnapshot;
    baselineUserMessageCount: number;
    baselineStopButtonVisible: boolean;
    baselineSendButtonVisible: boolean;
    baselineSendButtonEnabled: boolean;
    baselineChatSignalCount: number;
    baselineComposerValue: string;
    baselineSuggestedActionsVisible: boolean;
    timeoutMs: number;
  }): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    const assistantLocator = this.page.getByTestId("message-assistant");
    const userLocator = this.page.getByTestId("message-user");
    const spinnerLocator = this.page.getByTestId("message-assistant-loading");
    const stopButtonLocator = this.stopButton;
    const sendButtonLocator = this.sendButton;
    const suggestedActionsLocator = this.page.getByTestId("suggested-actions");
    let hasObservedStopButtonHidden = !baselineStopButtonVisible;
    let hasObservedSendButtonVisible = baselineSendButtonVisible;
    let hasObservedSendButtonEnabled = baselineSendButtonEnabled;
    let hasObservedSuggestedActionsHidden = !baselineSuggestedActionsVisible;
    const expectedComposerPrefill = this.pendingComposerPrefill;
    this.pendingComposerPrefill = null;
    let hasObservedComposerPrefill =
      !expectedComposerPrefill || expectedComposerPrefill.trim().length === 0;

    const baselineComposerTrimmed = baselineComposerValue.trim();

    while (Date.now() < deadline) {
      const [
        assistantCount,
        spinnerCount,
        stopVisible,
        sendVisible,
        sendEnabled,
        userCount,
        signalCount,
        composerValue,
        suggestedActionsVisible,
      ] = await Promise.all([
        assistantLocator.count().catch(() => 0),
        spinnerLocator.count().catch(() => 0),
        stopButtonLocator.isVisible().catch(() => false),
        sendButtonLocator.isVisible().catch(() => false),
        sendButtonLocator.isEnabled().catch(() => false),
        userLocator.count().catch(() => 0),
        this.page
          .evaluate(() => {
            const globalWindow = window as typeof window & {
              __PLAYWRIGHT_CHAT_SIGNALS__?: Array<unknown>;
            };

            return Array.isArray(globalWindow.__PLAYWRIGHT_CHAT_SIGNALS__)
              ? globalWindow.__PLAYWRIGHT_CHAT_SIGNALS__.length
              : 0;
          })
          .catch(() => 0),
        this.multimodalInput.inputValue().catch(() => ""),
        suggestedActionsLocator.isVisible().catch(() => false),
      ]);

      if (baselineSuggestedActionsVisible && !suggestedActionsVisible) {
        return;
      }

      if (!baselineSuggestedActionsVisible && suggestedActionsVisible && !hasObservedSuggestedActionsHidden) {
        hasObservedSuggestedActionsHidden = true;
      }

      if (signalCount > baselineChatSignalCount) {
        return;
      }

      if (assistantCount < baseline.count) {
        /**
         * Inline edit submissions briefly clear the trailing assistant reply
         * before reattaching a fresh bubble.  Detect the drop immediately so
         * the fallback acknowledges that streaming kicked off instead of
         * idling until the replacement content finishes rendering.
         */
        return;
      }

      if (spinnerCount > 0) {
        return;
      }

      const composerTrimmed = composerValue.trim();
      if (expectedComposerPrefill && !hasObservedComposerPrefill) {
        const expectedTrimmed = expectedComposerPrefill.trim();
        if (
          composerTrimmed.length > 0 &&
          (composerTrimmed === expectedTrimmed || composerValue === baselineComposerValue)
        ) {
          hasObservedComposerPrefill = true;
          await this.page.waitForTimeout(50);
          continue;
        }
      }

      if (baselineComposerTrimmed.length > 0) {
        if (composerTrimmed.length === 0 && composerValue !== baselineComposerValue) {
          if (hasObservedComposerPrefill || !expectedComposerPrefill) {
            return;
          }
        }
      }

      if (!sendVisible) {
        if (hasObservedSendButtonVisible) {
          return;
        }
      } else {
        if (!hasObservedSendButtonVisible) {
          hasObservedSendButtonVisible = true;
        }

        if (!sendEnabled && hasObservedSendButtonEnabled) {
          return;
        }

        if (sendEnabled && !hasObservedSendButtonEnabled) {
          hasObservedSendButtonEnabled = true;
        }
      }

      if (stopVisible) {
        if (!baselineStopButtonVisible) {
          return;
        }

        if (hasObservedStopButtonHidden) {
          return;
        }
      } else if (baselineStopButtonVisible && !hasObservedStopButtonHidden) {
        hasObservedStopButtonHidden = true;
      }

      if (userCount > baselineUserMessageCount) {
        return;
      }

      if (assistantCount > baseline.count) {
        return;
      }

      if (assistantCount > 0) {
        const latestAssistant = assistantLocator.nth(assistantCount - 1);
        const [
          latestId,
          latestStatus,
          latestText,
          latestArtifactCount,
        ] = await Promise.all([
          latestAssistant.getAttribute("data-message-id").catch(() => null),
          latestAssistant
            .getAttribute("data-message-status")
            .catch(() => null),
          latestAssistant
            .getByTestId("message-content")
            .innerText()
            .then((value) => value.trim())
            .catch(() => ""),
          latestAssistant
            .locator('[data-testid$="-artifact"]')
            .count()
            .catch(() => 0),
        ]);

        if (typeof latestStatus === "string" && latestStatus === "streaming") {
          /**
           * Inline edits reuse the existing assistant bubble while toggling its
           * lifecycle flag to `streaming`.  Treat that attribute change as
           * progress so the fallback no longer requires a DOM removal or text
           * mutation to acknowledge the regeneration.
           */
          return;
        }

        if (latestId && latestId !== baseline.latestMessageId) {
          return;
        }

        if (latestText !== baseline.latestMessageText) {
          return;
        }

        if (latestArtifactCount > baseline.latestArtifactCount) {
          return;
        }
      }

      await this.page.waitForTimeout(200);
    }

    throw new Error("Timed out waiting for chat UI to start streaming");
  }

  private async waitForVoteRequest(direction: "up" | "down"): Promise<void> {
    const response = await this.page.waitForResponse((candidate) => {
      const request = candidate.request();
      if (!request || request.method() !== "PATCH") {
        return false;
      }

      const rawUrl = candidate.url();
      try {
        const { pathname } = new URL(rawUrl);
        if (pathname !== "/api/vote") {
          return false;
        }
      } catch {
        if (!rawUrl.includes("/api/vote")) {
          return false;
        }
      }

      try {
        const parse =
          typeof request.postDataJSON === "function"
            ? request.postDataJSON.bind(request)
            : null;
        const body = parse ? parse() : {};
        return body?.type === direction;
      } catch {
        return true;
      }
    }, { timeout: 15_000 });

    if (!response.ok()) {
      const status = response.status();
      const statusText = response.statusText();
      throw new Error(
        `Vote request failed with ${status} ${statusText}`
      );
    }
  }

  /**
   * Inspect a rejected chat response and ensure the UI presented the
   * corresponding feedback toast. Returning a formatted error keeps the
   * surrounding network guard consistent between the request and response
   * branches while avoiding duplicate JSON parsing and toast assertions.
   */
  private async inspectRejectedChatResponse(
    response: PlaywrightResponse
  ): Promise<string> {
    const status = response.status();
    const statusText = response.statusText();

    let rawBody = "";

    try {
      rawBody = await response.text();
    } catch {
      rawBody = "";
    }

    const trimmedBody = rawBody.trim();

    let errorCode: string | null = null;
    let errorMessage: string | null = null;

    if (trimmedBody.length > 0) {
      let parsedBody: unknown = null;

      try {
        parsedBody = JSON.parse(trimmedBody);
      } catch {
        parsedBody = null;
      }

      if (parsedBody !== null) {
        const parsedEnvelope = chatErrorEnvelopeSchema.safeParse(parsedBody);

        if (parsedEnvelope.success && parsedEnvelope.data.error) {
          const envelope: ChatErrorEnvelope = parsedEnvelope.data;
          errorCode = envelope.error?.code ?? null;
          errorMessage = envelope.error?.message ?? null;
        }
      }
    }

    if (status === 403 && errorCode === "forbidden:chat") {
      const { toastCopy } = await this.expectForbiddenToast({
        errorCode,
        errorMessage,
      });

      return `Chat API rejected the request (403 Forbidden, code ${errorCode}) after surfacing a toast: "${toastCopy}"`;
    }

    const diagnosticBody = trimmedBody.slice(0, 1_000);
    const diagnostic = diagnosticBody.length > 0 ? ` – ${diagnosticBody}` : "";
    const resolvedStatusText = statusText || "Unknown";

    return `Chat API request failed with ${status} ${resolvedStatusText}${diagnostic}`;
  }

  /**
   * Ensure forbidden chat responses surface an actionable toast. Without this
   * guard hermetic Playwright runs would keep polling the DOM until the
   * timeout, hiding the real regression behind a vague "waiting for streaming"
   * error.
   */
  private async expectForbiddenToast({
    errorCode,
    errorMessage,
  }: {
    errorCode: string | null;
    errorMessage: string | null;
  }) {
    const toastLocator = this.page.locator(TOAST_LOCATOR).last();

    try {
      await toastLocator.waitFor({ state: "visible", timeout: 15_000 });
    } catch (error) {
      throw new Error(
        `Chat API responded with ${errorCode ?? "forbidden"} but no error toast became visible within 15 seconds.`
      );
    }

    let toastCopy = "";

    if (typeof toastLocator.innerText === "function") {
      try {
        toastCopy = (await toastLocator.innerText()).trim();
      } catch {
        toastCopy = "";
      }
    }

    if (!toastCopy) {
      throw new Error(
        `Chat API surfaced a forbidden response (${errorCode ?? "unknown"}) but the toast body was empty.`
      );
    }

    const candidateMessages = [
      errorMessage,
      "A regular account is required to use this feature.",
      "You need to sign in before continuing.",
      "You need to sign in to view this chat. Please sign in and try again.",
    ].filter((value): value is string => typeof value === "string");

    const normalizedToast = toastCopy.toLowerCase();

    if (
      candidateMessages.length > 0 &&
      !candidateMessages.some((candidate) =>
        normalizedToast.includes(candidate.toLowerCase())
      )
    ) {
      throw new Error(
        `Chat API surfaced an unexpected forbidden toast. Received: "${toastCopy}". Expected one of: ${candidateMessages.join(", ")}`
      );
    }

    return { toastCopy } as const;
  }

  async expectToastToContain(text: string) {
    await expect(this.page.locator(TOAST_LOCATOR).first()).toContainText(text);
  }

  async openSideBar() {
    const sidebarToggleButton = this.page.getByTestId("sidebar-toggle-button");
    await sidebarToggleButton.click();
  }

  isScrolledToBottom(): Promise<boolean> {
    return this.scrollContainer.evaluate(
      (el) => Math.abs(el.scrollHeight - el.scrollTop - el.clientHeight) < 1
    );
  }

  async waitForScrollToBottom(timeout = 5000): Promise<void> {
    const start = Date.now();

    while (Date.now() - start < timeout) {
      if (await this.isScrolledToBottom()) {
        return;
      }
      await this.page.waitForTimeout(100);
    }

    throw new Error(`Timed out waiting for scroll bottom after ${timeout}ms`);
  }

  async sendMultipleMessages(
    count: number,
    makeMessage: (i: number) => string
  ) {
    for (let i = 0; i < count; i++) {
      await this.sendUserMessage(makeMessage(i));
      await this.isGenerationComplete();
    }
  }

  async scrollToTop(): Promise<void> {
    await this.scrollContainer.evaluate((element) => {
      element.scrollTo({ top: 0, behavior: "auto" });
      /**
       * Programmatic scrolls in Playwright do not always emit the `scroll`
       * event, which means React’s listeners would miss the state change and
       * keep the "scroll to bottom" button hidden. Dispatch the event manually
       * so the UI mirrors a real user interaction.
       */
      element.dispatchEvent(new Event("scroll"));
    });
  }
}

function isTimeoutLikeError(error: unknown): boolean {
  if (!error) {
    return false;
  }

  if (error instanceof playwrightErrors.TimeoutError) {
    return true;
  }

  if (error instanceof Error) {
    if (error.name === "TimeoutError") {
      return true;
    }

    return error.message.toLowerCase().includes("timeout");
  }

  return false;
}
