import fs from "node:fs";
import path from "node:path";

import { expect, test } from "@playwright/test";

import {
  AUTH_DIR,
  CREDENTIALS_PATH,
  loadCredentials,
  type PersistedCredentials,
} from "../../utils/load-credentials";

const STATE_PATH = path.join(AUTH_DIR, "state.json");

/**
 * Snapshot the credential cache so the suite can mutate and restore it without
 * breaking the Playwright setup worker. When the cache is missing we synthesise
 * an empty baseline so the restoration step simply removes the generated file.
 */
function snapshotCredentialCache(): {
  readonly originalCredentials: PersistedCredentials | null;
  readonly originalFileContent: string | null;
} {
  if (!fs.existsSync(CREDENTIALS_PATH)) {
    return {
      originalCredentials: null,
      originalFileContent: null,
    };
  }

  const raw = fs.readFileSync(CREDENTIALS_PATH, "utf-8");
  try {
    const parsed = JSON.parse(raw) as PersistedCredentials;
    return {
      originalCredentials: parsed,
      originalFileContent: raw,
    };
  } catch (error) {
    throw new Error(
      "Existing Playwright credential cache is not valid JSON; aborting resilience test",
      error instanceof Error ? { cause: error } : undefined
    );
  }
}

/**
 * Restore the credential cache to its initial state so subsequent tests reuse
 * the same automation account provisioned by the setup worker.
 */
function restoreCredentialCache(
  baseline: ReturnType<typeof snapshotCredentialCache>
) {
  if (baseline.originalFileContent === null) {
    if (fs.existsSync(CREDENTIALS_PATH)) {
      fs.rmSync(CREDENTIALS_PATH, { force: true });
    }
    return;
  }

  fs.mkdirSync(AUTH_DIR, { recursive: true });
  fs.writeFileSync(CREDENTIALS_PATH, baseline.originalFileContent);
}

/**
 * Ensure the automation state snapshot remains consistent after the resilience
 * check. When we regenerate credentials we want Playwright to discard the
 * obsolete storage state, otherwise the stale session cookies would fail to
 * authenticate the new account.
 */
type StorageStateSnapshot = {
  readonly existed: boolean;
  readonly contents: string | null;
};

/**
 * Preserve the storage state snapshot generated by the setup worker so the
 * resilience test can restore it after mutating the cache. When the snapshot is
 * missing we remember that absence and mirror it during restoration to avoid
 * synthesising files that were never present to begin with.
 */
function snapshotStorageState(): StorageStateSnapshot {
  if (!fs.existsSync(STATE_PATH)) {
    return { existed: false, contents: null };
  }

  return {
    existed: true,
    contents: fs.readFileSync(STATE_PATH, "utf-8"),
  };
}

/**
 * Delete the automation storage state so the credential regeneration path can
 * validate that stale sessions are purged. The helper intentionally no-ops when
 * the file is already missing to keep the cleanup idempotent.
 */
function resetStorageStateSnapshot() {
  if (fs.existsSync(STATE_PATH)) {
    fs.rmSync(STATE_PATH, { force: true });
  }
}

/**
 * Restore the storage state snapshot captured before the resilience test
 * mutated the credential cache. Rehydrating the previous contents keeps the
 * downstream e2e projects (routes, additional UI suites, etc.) aligned with the
 * authenticated context provisioned by the setup worker.
 */
function restoreStorageStateSnapshot(baseline: StorageStateSnapshot) {
  if (!baseline.existed) {
    fs.rmSync(STATE_PATH, { force: true });
    return;
  }

  if (baseline.contents === null) {
    fs.rmSync(STATE_PATH, { force: true });
    return;
  }

  fs.mkdirSync(AUTH_DIR, { recursive: true });
  fs.writeFileSync(STATE_PATH, baseline.contents);
}

/**
 * The resilience test deliberately corrupts the persisted credentials and
 * asserts that the helper regenerates them using the fallback environment
 * variables. The regeneration should also rewrite the cache on disk so the
 * setup worker can provision the matching automation account during the next
 * run.
 */
test.describe("Playwright credential resilience", () => {
  test("rebuilds the automation credentials after detecting corrupted JSON", async () => {
    const baseline = snapshotCredentialCache();
    const stateBaseline = snapshotStorageState();

    const warnings: unknown[][] = [];
    const originalWarn = console.warn;
    console.warn = (...args: unknown[]) => {
      warnings.push(args);
    };

    try {
      fs.mkdirSync(AUTH_DIR, { recursive: true });
      fs.writeFileSync(CREDENTIALS_PATH, "{not-json");

      const fallbackEmail =
        baseline.originalCredentials?.email ?? "corrupted-playwright@example.com";
      const fallbackPassword =
        baseline.originalCredentials?.password ?? "Corrupted123!";

      process.env.E2E_USER_EMAIL = fallbackEmail;
      process.env.E2E_USER_PASSWORD = fallbackPassword;

      resetStorageStateSnapshot();

      const credentials = loadCredentials();

      expect(credentials).toEqual({
        email: fallbackEmail,
        password: fallbackPassword,
      });

      expect(warnings.length).toBeGreaterThanOrEqual(1);
      expect(String(warnings[0]?.[0])).toContain(
        "Failed to parse persisted Playwright credentials"
      );

      const persisted = JSON.parse(
        fs.readFileSync(CREDENTIALS_PATH, "utf-8")
      ) as PersistedCredentials;
      expect(persisted).toEqual(credentials);
    } finally {
      restoreCredentialCache(baseline);
      restoreStorageStateSnapshot(stateBaseline);
      delete process.env.E2E_USER_EMAIL;
      delete process.env.E2E_USER_PASSWORD;
      console.warn = originalWarn;
    }
  });
});
